-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 20, 2024 at 12:16 PM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `travelime`
--

-- --------------------------------------------------------

--
-- Table structure for table `hotels`
--

CREATE TABLE `hotels` (
  `id` int(11) NOT NULL,
  `hotelsJSON` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`hotelsJSON`)),
  `userId` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `hotels`
--

INSERT INTO `hotels` (`id`, `hotelsJSON`, `userId`) VALUES
(1, '[{\"hotelName\":\"Bubble Mutts Dog Wash\",\"hotelId\":\"ChIJrcx7urDLQIYRKazM0_ZBXQM\",\"hotelImage\":\"https:\\/\\/maps.googleapis.com\\/maps\\/api\\/place\\/js\\/PhotoService.GetPhoto?1sAUc7tXUkKeXrEKo6nBSChtxPk7M_D06g_IWIKDPfIErHCy4fri_ACVmuuxGJe0phTyIJ9zSP03SiC0-87dm6Sv5h401p8R0RKQ0glq_CHkoh66grpcqtHwKBHgkrD9_tyVn7OiOZ6l_v2Eqe9OwWc23-xhp9k3JFbOG0zIl02218KHMzSH2T&3u3024&5m1&2e1&callback=none&r_url=https%3A%2F%2F10.122.69.57%2FTravelime%2Fhotels&key=AIzaSyAzabKtWQq9f72-mTg661g_KQQGdgO7Sq8&token=39793\",\"hotelRating\":4.7},{\"hotelName\":\"Cuanza sul\",\"hotelId\":\"ChIJGW51BQDzyxsReUUCwKTkxuA\",\"hotelImage\":\"https:\\/\\/maps.googleapis.com\\/maps\\/api\\/place\\/js\\/PhotoService.GetPhoto?1sAUc7tXXwBN7vNqOT5RCkNfkxe-cbz7dlCsJdLZqpMXOzwa74fsx8hTlc7BSmDFxhyCTSpDd52Q1gOupF0_SG5ZFAJ9UGa2ydgjW5E5WnLE3QS63ynZcJMLpJrSvU7WkUwZOTHL3vk4WGj4HyXAX5iXUGXq140zJpGrXtlnZlJi0sIfCGdFF2&3u1200&5m1&2e1&callback=none&r_url=https%3A%2F%2F10.122.69.57%2FTravelime%2Fhotels%2FAngola&key=AIzaSyAzabKtWQq9f72-mTg661g_KQQGdgO7Sq8&token=20766\",\"hotelRating\":5},{\"hotelName\":\"nrjiobanna Tavera\",\"hotelId\":\"ChIJ6-f1n9CHzhARmENa-_44y_Y\",\"hotelImage\":\"https:\\/\\/maps.googleapis.com\\/maps\\/api\\/place\\/js\\/PhotoService.GetPhoto?1sAUc7tXVXojzhPd5Z2Y3JQZsgrtPJyhqYLSjUf6jfje531xpUJtAxn9mfScspmI9fw5jNoz2cplEZI0pe7tjuGRVw5wOfVA9CIu35NduzzqvpjpL7mTEYS1DaAJmU_kYDQsnNvbV8wKMsUNCaufqj388BKx4FbgahE73AVpaFE8Rb4D6g9qLX&3u1030&5m1&2e1&callback=none&r_url=https%3A%2F%2F10.122.69.57%2FTravelime%2Fhotels%2FCentral%2520african%2520republic&key=AIzaSyAzabKtWQq9f72-mTg661g_KQQGdgO7Sq8&token=89004\",\"hotelRating\":null}]', 1),
(2, '[]', 2),
(3, '[]', 4),
(4, '[]', 5);

-- --------------------------------------------------------

--
-- Table structure for table `traveladvice`
--

CREATE TABLE `traveladvice` (
  `countryID` int(11) NOT NULL,
  `countryName` varchar(255) CHARACTER SET utf8 NOT NULL,
  `countryCode` varchar(255) CHARACTER SET utf8 NOT NULL,
  `countryDescription` text CHARACTER SET utf8 NOT NULL,
  `countryKeywords` varchar(255) CHARACTER SET utf8 NOT NULL,
  `countryCapital` varchar(255) CHARACTER SET utf8 NOT NULL,
  `countryMajorCities` varchar(255) CHARACTER SET utf8 NOT NULL,
  `countryLanguages` varchar(255) CHARACTER SET utf8 NOT NULL,
  `countryCurrency` varchar(255) CHARACTER SET utf8 NOT NULL,
  `countryImage` text CHARACTER SET utf8 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `traveladvice`
--

INSERT INTO `traveladvice` (`countryID`, `countryName`, `countryCode`, `countryDescription`, `countryKeywords`, `countryCapital`, `countryMajorCities`, `countryLanguages`, `countryCurrency`, `countryImage`) VALUES
(1, 'Afghanistan', 'AF', 'Nestled in the heart of Asia, Afghanistan is a land of rugged beauty and ancient history. Despite its tumultuous past, it boasts stunning landscapes ranging from towering mountains to fertile valleys. Visitors can explore historic sites like the Bamiyan Buddhas and experience the hospitality of its diverse cultures.', 'Mountains, Kabul, Culture, History, Hospitality', 'Kabul', 'Kabul, Kandahar, Herat, Mazar-i-Sharif', 'Pashto, Dari', 'Afghani', 'https://udayton.edu/magazine/2021/08/images/2108_afganistan_island.jpg'),
(2, 'Albania', 'AL', 'Tucked away in southeastern Europe, Albania is a hidden gem with a rich history and natural wonders. From the ancient ruins of Butrint to the pristine beaches of the Albanian Riviera, it offers a mix of cultural heritage and stunning landscapes. Visitors can also explore vibrant cities like Tirana and experience the warmth of Albanian hospitality.', 'Mountains, Riviera, Ancient, Culture, Ottoman', 'Tirana', 'Tirana, Durrës, Vlorë, Shkodër', 'Albanian', 'Lek', 'https://www.state.gov/wp-content/uploads/2018/11/Albania-2218x1406.jpg'),
(3, 'Algeria', 'DZ', 'With its vast Sahara Desert landscapes and Mediterranean coastlines, Algeria offers a tapestry of contrasts and beauty. Rich in history and culture, it boasts ancient Roman ruins like Timgad and diverse landscapes ranging from the Atlas Mountains to the Tassili n\'Ajjer National Park. Visitors can immerse themselves in Berber traditions, sample delicious Algerian cuisine, and explore the vibrant markets of cities like Algiers.', 'Sahara, Culture, History, Cuisine, Heritage', 'Algiers', 'Algiers, Oran, Constantine, Annaba', 'Arabic, Berber', 'Dinar', 'https://www.state.gov/wp-content/uploads/2019/04/shutterstock_11771813523.jpg'),
(4, 'Andorra', 'AD', 'Nestled in the Pyrenees mountains between France and Spain, Andorra is a tiny principality known for its stunning mountain landscapes and tax-free shopping. Visitors can explore charming villages like Andorra la Vella, indulge in outdoor activities like skiing and hiking, and marvel at medieval landmarks such as the Sant Joan de Caselles church.', 'Mountains, Skiing, Shopping, Cuisine, Adventure', 'Andorra la Vella', 'Andorra la Vella, Escaldes-Engordany, Encamp, Sant Julià de Lòria', 'Catalan', 'Euro', 'https://freedomhouse.org/sites/default/files/2020-02/Andorra__Country_portal_shutterstock_1446148013-127_SELECTION.jpg'),
(5, 'Angola', 'AO', 'Located on the west coast of Southern Africa, Angola is a country of diverse landscapes, from pristine beaches along the Atlantic coast to lush rainforests and the arid beauty of the Namib Desert. Despite its troubled past, Angola is emerging as a tourist destination with attractions such as the Kalandula Falls, colonial architecture in Luanda, and wildlife-rich national parks like Quiçama National Park.', 'Safari, Beaches, Music, Culture, Wildlife', 'Luanda', 'Luanda, Huambo, Lobito, Benguela', 'Portuguese', 'Kwanza', 'https://www.thuisvaccinatie.nl/wp-content/uploads/angola-1920x0-c-default.png'),
(6, 'Anguilla', 'AI', 'A tranquil island paradise in the Caribbean, Anguilla is renowned for its pristine white-sand beaches, turquoise waters, and luxurious resorts. Visitors can enjoy water sports like snorkeling and sailing, explore secluded coves, and savor the island\'s vibrant culinary scene, which blends local flavors with international influences.', 'Beaches, Tranquility, Luxury, Cuisine, Sailing', 'The Valley', 'The Valley', 'English', 'East Caribbean Dollar', 'https://www.travelandleisure.com/thmb/HZwBXTkzXKhrUUPHEPB9N5vhedU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/TAL-shoal-bay-TODOANGUILLA0723-18c347b622c642bf88eaa9be74981edc.jpg'),
(7, 'Antigua & Barbuda', 'AG', 'This twin-island nation in the Caribbean is renowned for its stunning beaches, vibrant culture, and rich history. Antigua boasts 365 beaches—one for each day of the year—where visitors can relax on powdery white sands or indulge in water sports like snorkeling and sailing. Meanwhile, Barbuda offers a more secluded retreat, with pristine pink beaches and abundant wildlife, including the famous Frigate Bird Sanctuary.', 'Beaches, Sailing, Luxury, History, Carnival', 'St. John\'s', 'St. John\'s, All Saints, Liberta', 'English', 'East Caribbean Dollar', 'https://a.cdn-hotels.com/gdcs/production111/d641/9f5687f8-b1a2-4ace-8e71-fb2586461290.jpg?impolicy=fcrop&w=800&h=533&q=medium'),
(8, 'Argentina', 'AR', 'From the vibrant streets of Buenos Aires to the breathtaking landscapes of Patagonia, Argentina offers a diverse array of experiences. Tango performances in Buenos Aires, the majestic Iguazú Falls, the otherworldly landscapes of the Andes Mountains, and the rugged beauty of Argentine Patagonia are just a few highlights. Culinary delights such as Argentine beef and Malbec wine further enrich the visitor\'s experience in this vast and captivating country.', 'Tango, Steak, Wine, Patagonia, Football', 'Buenos Aires', 'Buenos Aires, Córdoba, Rosario, Mendoza', 'Spanish', 'Peso', 'https://www.thetimes.co.uk/imageserver/image/%2Fmethode%2Ftimes%2Fprod%2Fweb%2Fbin%2F9a95117e-6bf1-4b42-ac77-b1a412f3b73d.jpg?crop=5000%2C3333%2C0%2C0'),
(9, 'Armenia', 'AM', 'Nestled in the Caucasus region between Europe and Asia, Armenia is a land of ancient history, stunning landscapes, and warm hospitality. Visitors can explore UNESCO World Heritage sites like the Geghard Monastery and the Temple of Garni, hike through the dramatic scenery of the Armenian Highlands, and sample traditional cuisine such as lavash (flatbread) and dolma (stuffed grape leaves).', 'History, Monasteries, Hospitality, Cuisine, Culture', 'Yerevan', 'Yerevan, Gyumri, Vanadzor, Hrazdan', 'Armenian', 'Dram', 'https://ichef.bbci.co.uk/news/976/cpsprodpb/9AEA/production/_129285693_gettyimages-853983104.jpg'),
(10, 'Aruba', 'AW', 'Situated in the southern Caribbean, Aruba is known for its stunning beaches, vibrant culture, and warm, sunny weather year-round. Visitors can unwind on the powdery white sands of Eagle Beach, explore colorful underwater marine life while snorkeling or diving, and experience the lively atmosphere of Oranjestad, the capital city, with its Dutch colonial architecture and bustling markets.', 'Beaches, Diving, Windsurfing, Cuisine, Carnival', 'Oranjestad', 'Oranjestad, Noord, Santa Cruz, San Nicolas', 'Dutch, Papiamento', 'Aruban florin', 'https://www.vakantiediscounter.nl/blog/wp-content/uploads/2022/11/wat-te-doen-aruba.jpg'),
(11, 'Australia', 'AU', 'The vast continent of Australia offers an abundance of natural wonders, from the iconic Sydney Opera House and Harbour Bridge to the majestic Great Barrier Reef and the rugged Outback. Visitors can explore vibrant cities like Sydney, Melbourne, and Brisbane, encounter unique wildlife such as kangaroos and koalas, and immerse themselves in Indigenous culture and ancient landscapes.', 'Outback, Beaches, Wildlife, Cities, Surfing', 'Canberra', 'Sydney, Melbourne, Brisbane, Perth', 'English', 'Australian Dollar', 'https://content.r9cdn.net/rimg/dimg/43/4b/72c43e11-city-2258-17a3a42c3ab.jpg?crop=true&width=1366&height=768&xhint=1597&yhint=1522'),
(12, 'Austria', 'AT', 'Nestled in the heart of Europe, Austria is a land of alpine beauty, rich history, and cultural heritage. Visitors can marvel at architectural masterpieces like Vienna\'s Schönbrunn Palace and Salzburg\'s Hohensalzburg Fortress, ski in the Tyrolean Alps, and enjoy the musical legacy of composers like Mozart and Strauss in cities renowned for classical music and opera.', 'Alps, Music, History, Architecture, Skiing', 'Vienna', 'Vienna, Graz, Linz, Salzburg', 'German', 'Euro', 'https://content.r9cdn.net/rimg/dimg/a8/ce/6d1490d1-city-64466-16510215367.jpg?width=1366&height=768&xhint=1426&yhint=1115&crop=true'),
(13, 'Azerbaijan', 'AZ', 'Situated at the crossroads of Europe and Asia, Azerbaijan is a country of contrasts, blending ancient traditions with modernity. Visitors can explore the historic streets of Baku\'s Old City, marvel at the futuristic Flame Towers, and discover the natural beauty of places like the mud volcanoes of Gobustan and the Caucasus Mountains.', 'Cuisine, Silk Road, Architecture, Culture, Caspian', 'Baku', 'Baku, Ganja, Sumqayit, Mingachevir', 'Azerbaijani', 'Manat', 'https://keystoneacademic-res.cloudinary.com/image/upload/v1696411259/articles/educationscom/article-hero-image-2991.jpg'),
(14, 'Bahamas', 'BS', 'A tropical paradise in the Atlantic Ocean, the Bahamas is renowned for its stunning beaches, clear turquoise waters, and vibrant coral reefs. Visitors can relax on the powdery sands of Nassau\'s Cable Beach, swim with dolphins in Freeport, or explore the secluded cays and islands of the Exumas.', 'Beaches, Coral, Luxury, Paradise, Music', 'Nassau', 'Nassau, Freeport, West End, Coopers Town', 'English', 'Bahamian Dollar', 'https://www.kayak.nl/rimg/dimg/db/25/fd914ac8-city-11232-1708c88cf11.jpg?width=1366&height=768&xhint=2270&yhint=1918&crop=true'),
(15, 'Bahrain', 'BH', 'A small island nation in the Arabian Gulf, Bahrain is known for its rich history, modern skyline, and cultural heritage. Visitors can explore ancient archaeological sites like the Bahrain Fort and Barbar Temple, shop in bustling souks, and relax on the beaches of Amwaj Islands or Al Jazair.', 'Pearls, Culture, Hospitality, Skyscrapers, Formula1', 'Manama', 'Manama, Riffa, Muharraq, Hamad Town', 'Arabic', 'Bahraini Dinar', 'https://statemag.state.gov/wp-content/uploads/2019/12/cropped-0120POM-17.jpg'),
(16, 'Bangladesh', 'BD', 'Located in South Asia, Bangladesh is a land of rivers, lush greenery, and vibrant culture. Visitors can explore historic sites like the Sundarbans mangrove forest, home to the Bengal tiger, and the ancient city of Paharpur, as well as experience the hustle and bustle of cities like Dhaka and Chattogram.\n', 'Rivers, Culture, Cuisine, Sundarbans, Heritage', 'Dhaka', 'Dhaka, Chittagong, Khulna, Rajshahi', 'Bengali', 'Taka', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/04/c3/86/03/paharpur-buddhist-monastery.jpg?w=1200&h=1200&s=1'),
(17, 'Barbados', 'BB', 'A Caribbean island nation, Barbados is known for its beautiful beaches, vibrant culture, and colonial architecture. Visitors can relax on the pristine sands of Crane Beach, explore historic plantations like St. Nicholas Abbey, and immerse themselves in the lively atmosphere of Bridgetown, the capital city.\n', 'Beaches, Rum, Music, Cricket, Festivals', 'Bridgetown', 'Bridgetown, Speightstown, Oistins, Bathsheba', 'English', 'Barbadian Dollar', 'https://www.kayak.nl/rimg/dimg/62/45/9f8e96e2-city-24905-1798a9e9030.jpg?width=1366&height=768&xhint=2837&yhint=1711&crop=true'),
(18, 'Belarus', 'BY', 'Situated in Eastern Europe, Belarus is known for its dense forests, picturesque villages, and Soviet-era architecture. Visitors can explore historic sites like Mir Castle and Nesvizh Palace, wander through the charming streets of Minsk, and experience the warm hospitality of its people.\n', 'Forests, Lakes, Culture, History, Hospitality', 'Minsk', 'Minsk, Gomel, Mogilev, Vitebsk', 'Belarusian, Russian', 'Belarusian Ruble', 'https://www.state.gov/wp-content/uploads/2023/07/shutterstock_150664154v2-2109x1406.jpg'),
(19, 'Belgium', 'BE', 'Located in Western Europe, Belgium is famous for its medieval towns, delicious chocolates, and world-renowned beer. Visitors can explore the historic city centers of Brussels, Bruges, and Ghent, marvel at architectural gems like the Grand Place, and indulge in culinary delights such as moules-frites and Belgian waffles.\n', 'Chocolate, Beer, Waffles, Architecture, History', 'Brussels', 'Brussels, Antwerp, Ghent, Bruges', 'Dutch, French, German', 'Euro', 'https://lp-cms-production.imgix.net/2022-05/GettyRF_597070535.jpg?auto=format&w=1920&h=640&fit=crop&crop=faces,edges&q=75'),
(20, 'Belize', 'BZ', 'Belize, located on the northeastern coast of Central America, is renowned for its stunning barrier reef, lush rainforests, and diverse wildlife. Visitors can snorkel or dive among colorful coral formations, explore ancient Mayan ruins like Caracol and Xunantunich, and immerse themselves in the rich culture of its Garifuna and Maya communities.\n', 'Reefs, Rainforest, Mayan, Adventure, Culture', 'Belmopan', 'Belmopan, Belize City, San Ignacio, Orange Walk Town', 'English', 'Belize Dollar', 'https://media.timeout.com/images/105239971/image.jpg'),
(21, 'Benin', 'BJ', 'Located in West Africa, Benin is known for its rich history, vibrant culture, and diverse landscapes. Visitors can explore ancient royal palaces in Abomey, witness traditional voodoo ceremonies, and relax on the pristine beaches along the Atlantic coast.\n', 'Voodoo, History, Culture, Nature, Markets', 'Porto-Novo', 'Porto-Novo, Cotonou, Parakou, Djougou', 'French', 'West African CFA franc', 'https://www.bradtguides.com/wp-content/uploads/2020/12/ganvie-benin-laurent-nilles-scaled.jpg'),
(22, 'Bermuda', 'BM', 'A British Overseas Territory in the North Atlantic Ocean, Bermuda is famous for its pink-sand beaches, turquoise waters, and distinctive pastel-colored houses. Visitors can explore historic sites like the Royal Naval Dockyard, snorkel among shipwrecks in the crystal-clear waters, and enjoy world-class golfing and sailing.\n', 'Beaches, Pink Sand, History, Sailing, Triangle', 'Hamilton', 'Hamilton, St. George\'s, Somerset Village, Flatts Village', 'English', 'Bermudian Dollar', 'https://www.tripsavvy.com/thmb/dvgOg72VR2ghBTIekOnMdY6eMMQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/TimMLanthier-eced7b2434724a9a9bf3cc7733834c13.jpg'),
(23, 'Bhutan', 'BT', 'Nestled in the eastern Himalayas, Bhutan is known for its stunning mountain scenery, ancient monasteries, and unique cultural traditions. Visitors can trek through pristine landscapes, visit sacred sites like the Taktsang Monastery (Tiger\'s Nest), and experience the country\'s Gross National Happiness philosophy firsthand.\n', 'Himalayas, Monasteries, Happiness, Trekking, Culture', 'Thimphu', 'Thimphu, Phuntsholing, Paro, Punakha', 'Dzongkha', 'Ngultrum', 'https://good-nature-blog-uploads.s3.amazonaws.com/uploads/2022/04/Bhutan-mountain-1-2.jpg'),
(24, 'Bolivia', 'BO', 'Situated in the heart of South America, Bolivia is known for its breathtaking landscapes, including the otherworldly Salar de Uyuni salt flats, the rugged Andean mountains, and the Amazon rainforest. Visitors can explore colonial cities like Sucre and Potosí, trek to ancient Inca ruins, and experience the rich culture of indigenous communities.\n', 'Andes, Salt Flats, Culture, Nature, Adventure', 'Sucre', 'La Paz, Santa Cruz, Cochabamba, Oruro', 'Spanish, Quechua, Aymara', 'Boliviano', 'https://www.state.gov/wp-content/uploads/2019/04/shutterstock_1030504030v2-2109x1406-1.jpg'),
(25, 'Bosnia & Herzegovina', 'BA', 'Located in the Balkans, Bosnia and Herzegovina is known for its stunning natural beauty, rich history, and diverse cultural heritage. Visitors can explore the historic streets of Sarajevo, marvel at the beauty of Mostar\'s Old Bridge, and discover hidden gems like the medieval town of Jajce and the picturesque village of Blagaj.\n', 'History, Ottoman, Nature, Culture, Cuisine', 'Sarajevo', 'Sarajevo, Banja Luka, Tuzla, Mostar', 'Bosnian, Croatian, Serbian', 'Convertible Mark', 'https://i.natgeofe.com/k/56db8db3-a139-41b9-885f-d3c5f3623343/bosnia-and-herzegovina-mostar-city_3x2.jpg?wp=1&w=1084.125&h=721.875'),
(26, 'Botswana', 'BW', 'A landlocked country in Southern Africa, Botswana is renowned for its vast wilderness areas, including the Okavango Delta, Chobe National Park, and the Kalahari Desert. Visitors can embark on safaris to see abundant wildlife such as elephants, lions, and giraffes, and experience the tranquility of the African bush.\n', 'Safari, Wildlife, Delta, Culture, Adventure', 'Gaborone', 'Gaborone, Francistown, Molepolole, Maun', 'English, Tswana', 'Pula', 'https://www.andbeyond.com/wp-content/uploads/sites/5/Herd-of-Elephants-walking-while-guests-cross-channel-on-a-Safari-Game-Drive-in-Botswana.jpg'),
(27, 'Brazil', 'BR', 'The largest country in South America, known for its Amazon rainforest, Christ the Redeemer statue, and Carnaval festival.', 'Amazon, Carnaval, Football, Beaches, Music', 'Brasília', 'São Paulo, Rio de Janeiro, Brasília, Salvador', 'Portuguese', 'Real', 'https://www.celebritycruises.com/blog/content/uploads/2021/09/what-is-brazil-known-for-christ-the-redeemer-aerial-hero.jpg'),
(28, 'British Virgin Islands', 'IO', 'A British Overseas Territory in the Caribbean, comprising four main islands and many smaller ones.', 'Sailing, Beaches, Luxury, Nature, Tranquility', 'Road Town', 'Road Town, Spanish Town, The Settlement, Great Harbour', 'English', 'US Dollar', 'https://www.travelandleisure.com/thmb/kc3YV5yyG3ZyI8ddfkCLmqIyJdo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/jost-van-dyke-british-virgin-islands-caribbean-BVI0310-462b5a66d0974dbcbd69a2240c10031d.jpg'),
(29, 'Brunei', 'BN', 'A small nation on the island of Borneo, known for its beaches and biodiverse rainforest.', 'Oil, Islam, Rainforest, Culture, Luxury', 'Bandar Seri Begawan', 'Bandar Seri Begawan, Kuala Belait, Seria, Tutong', 'Malay', 'Brunei Dollar', 'https://mediaim.expedia.com/destination/1/bb6ec6e87fe6f5e18708d30cb9a3670c.jpg'),
(30, 'Bulgaria', 'BG', 'A Balkan nation with diverse terrain encompassing Black Sea coastline, a mountainous interior, and rivers, including the Danube.', 'Mountains, Beaches, Culture, History, Roses', 'Sofia', 'Sofia, Plovdiv, Varna, Burgas', 'Bulgarian', 'Lev', 'https://www.state.gov/wp-content/uploads/2018/11/Bulgaria-2560x1387.jpg'),
(31, 'Burkina Faso', 'BF', 'A landlocked country in West Africa, known for its art and culture.', 'Culture, Wildlife, Music, Handicrafts, Hospitality', 'Ouagadougou', 'Ouagadougou, Bobo-Dioulasso, Koudougou, Banfora', 'French', 'West African CFA franc', 'https://media.cntraveler.com/photos/569e792d78d099fc1224a29f/master/pass/burkina-faso-04-cr-getty.jpg'),
(32, 'Burundi', 'BI', 'A landlocked country in East Africa, known for its coffee and tea industry and scenic landscapes.', 'Culture, Wildlife, Lakes, Tea, History', 'Gitega', 'Gitega, Bujumbura, Ngozi, Muyinga', 'Kirundi, French', 'Burundi Franc', 'https://www.africa.com/wp-content/uploads/2019/02/burundi-image.jpg'),
(33, 'Cambodia', 'KH', 'A Southeast Asian nation with landscapes spanning low-lying plains, the Mekong Delta, mountains, and Gulf of Thailand coastline.', 'Temples, Angkor, Cuisine, Culture, History', 'Phnom Penh', 'Phnom Penh, Siem Reap, Battambang, Sihanoukville', 'Khmer', 'Riel', 'https://cdn.britannica.com/24/77424-050-4FF80B58/Angkor-Wat-Cambodia.jpg'),
(34, 'Cameroon', 'CM', 'A Central African country with varied terrain and wildlife, offering diverse cultural and natural experiences.', 'Culture, Wildlife, Diversity, Cuisine, Music', 'Yaoundé', 'Yaoundé, Douala, Garoua, Bamenda', 'French, English', 'Central African CFA franc', 'https://i.natgeofe.com/k/29882706-fcf0-42bf-b16e-62f88a58b713/Cameroon-valley.jpg'),
(35, 'Canada', 'CA', 'The second-largest country in the world by total area, known for its diverse landscapes and multicultural cities.', 'Nature, Wilderness, Cities, Hockey, Diversity', 'Ottawa', 'Toronto, Vancouver, Montreal, Calgary', 'English, French', 'Canadian Dollar', 'https://www.sundowner.nl/wp-content/uploads/Rondreis-Canada-3.jpg'),
(36, 'Cape Verde', 'CV', 'An island country spanning an archipelago of 10 volcanic islands in the central Atlantic Ocean.', 'Beaches, Volcanoes, Music, Culture, Hospitality', 'Praia', 'Praia, Mindelo, Santa Maria, Assomada', 'Portuguese', 'Cape Verdean Escudo', 'https://misstourist.com/wp-content/uploads/2023/10/1-0-Santa-Maria-beach.jpg'),
(37, 'Cayman Islands', 'KY', 'A British Overseas Territory in the western Caribbean Sea, known for its beach resorts, scuba diving, and offshore financial services.', 'Beaches, Diving, Finance, Luxury, Nature', 'George Town', 'George Town, West Bay, Bodden Town, East End', 'English', 'Cayman Islands Dollar', 'https://www.msccruises.nl/-/media/global-contents/destinations/ports/cayman-islands/georgetown/cruise-to-georgetown-cayman-islands.jpg?bc=transparent&as=1&dmc=0&iar=0&mh=1395&mw=2460&sc=0&thn=0&udi=0&hash=789C000AF35BB80F1EEEC74216EF6CDF'),
(38, 'Central African Republic', 'CF', 'A landlocked country in Central Africa known for its biodiversity and national parks.', 'Wildlife, Forests, Culture, Diamonds, Hospitality', 'Bangui', 'Bangui, Bimbo, Berbérati, Carnot', 'French, Sango', 'Central African CFA franc', 'https://facts.net/wp-content/uploads/2023/06/48-facts-about-central-african-republic-1688034946.jpg'),
(39, 'Chad', 'TD', 'A landlocked country in north-central Africa known for its desert landscapes and Lake Chad.', 'Desert, Lakes, Culture, Wildlife, Sahel', 'N\'Djamena', 'N\'Djamena, Moundou, Sarh, Abéché', 'French, Arabic', 'Central African CFA franc', 'https://www.rjtravelagency.com/wp-content/uploads/2023/05/UNESCO-World-Heritage-Sites-in-Chad.jpg'),
(40, 'Chile', 'CL', 'A long, narrow country stretching along South America\'s western edge, with over 6,000 km of Pacific Ocean coastline.', 'Andes, Wine, Patagonia, Culture, Coast', 'Santiago', 'Santiago, Valparaíso, Concepción, La Serena', 'Spanish', 'Chilean Peso', 'https://www.state.gov/wp-content/uploads/2019/04/Chile-e1556024428830-2496x1406.jpg'),
(41, 'China', 'CN', 'A populous nation in East Asia whose vast landscape encompasses grassland, desert, mountains, lakes, rivers, and more than 14,000 km of coastline.', 'Great Wall, Cuisine, Culture, History, Megacities', 'Beijing', 'Beijing, Shanghai, Guangzhou, Shenzhen', 'Mandarin', 'Renminbi (Yuan)', 'https://merk.anwb.nl/transform/57ae145f-3516-49a7-b9ba-c39fc43a8a6f/china_peking_beijing_chinese-muur_uitzicht_overzicht_zon_b?io=height%3A512%2Ctransform%3Afill%2Cwidth%3A3425'),
(42, 'Colombia', 'CO', 'A country at the northern tip of South America known for its coffee, culture, and diverse landscapes.', 'Coffee, Caribbean, Culture, Nature, Salsa', 'Bogotá', 'Bogotá, Medellín, Cali, Cartagena', 'Spanish', 'Colombian Peso', 'https://media.cntraveler.com/photos/5a00c56ce1a12132221cfac3/16:9/w_2560%2Cc_limit/Colombia_GettyImages-150953681.jpg'),
(43, 'Congo', 'CG', 'A central African nation with vast swaths of tropical rainforest and numerous rivers.', 'Rainforest, Wildlife, Culture, Music, Diamonds', 'Brazzaville', 'Brazzaville, Pointe-Noire, Dolisie, Nkayi', 'French, Lingala', 'Central African CFA franc', 'https://borgenproject.org/wp-content/uploads/Congo-2.jpg'),
(44, 'Cook Islands', 'CK', 'A nation in the South Pacific, with political links to New Zealand, comprising 15 islands scattered over a vast area.', 'Beaches, Lagoon, Culture, Hospitality, Paradise', 'Avarua', 'Avarua, Arutanga, Omoka, Tauhunu', 'English, Cook Islands Māori', 'New Zealand Dollar', 'https://www.goway.com/static/author-hero-bc1c42d3868a64f674a983f54bb90d51.jpeg'),
(45, 'Costa Rica', 'CR', 'A rugged, rainforested Central American country with coastlines on the Caribbean and Pacific.', 'Rainforest, Wildlife, Eco-tourism, Beaches, Pura Vida', 'San José', 'San José, Limón, Alajuela, Heredia', 'Spanish', 'Costa Rican Colón', 'https://media.weflycheap.be/eyJidWNrZXQiOiJ3ZWZseWNoZWFwIiwia2V5IjoiNmYwZDM4YzI1MThlNGFmMmJiODFmODAxMzk1MjkzNzlfdXJsXzg5MTE1LmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6Mzg0MCwiZml0IjoiaW5zaWRlIiwicXVhbGl0eSI6NzV9fX0='),
(46, 'Cote D Ivoire', 'CI', 'A West African country with beach resorts, rainforests, and a French-colonial legacy.', 'Culture, Cocoa, Beaches, Music, Diversity', 'Yamoussoukro', 'Abidjan, Yamoussoukro, Bouaké, Daloa', 'French', 'West African CFA franc', 'https://ongolo.com/wp-content/uploads/2024/01/shutterstock_1091969669-1024x683.jpeg'),
(47, 'Croatia', 'HR', 'A country at the crossroads of Central and Southeast Europe on the Adriatic Sea.', 'Coastline, Dubrovnik, Islands, History, Nature', 'Zagreb', 'Zagreb, Split, Rijeka, Osijek', 'Croatian', 'Kuna', 'https://afar.brightspotcdn.com/dims4/default/d2828ee/2147483647/strip/true/crop/3000x1592+0+90/resize/1440x764!/quality/90/?url=https%3A%2F%2Fafar-media-production-web.s3.us-west-2.amazonaws.com%2Fbrightspot%2Fcd%2F68%2F65a13b884896afba4b1cfd6fa0db%2Ftravelguides-crotia-brendanvanson-shutterstock.jpg'),
(48, 'Cuba', 'CU', 'A Caribbean island nation under communist rule known for its beaches, colonial architecture, and cigars.', 'Cigars, Music, Culture, Beaches, History', 'Havana', 'Havana, Santiago de Cuba, Camagüey, Holguín', 'Spanish', 'Cuban Peso', 'https://media.weflycheap.nl/eyJidWNrZXQiOiJ3ZWZseWNoZWFwIiwia2V5IjoiNDA4YjNmNjkzYTU2NDk0Mzg2NTU2NmZjNWVjZmI5OTBfdXJsXzMzNjU2LmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6Mzg0MCwiZml0IjoiaW5zaWRlIiwicXVhbGl0eSI6NzV9fX0='),
(49, 'Curacao', 'CW', 'A Dutch Caribbean island known for its beaches tucked into coves and its expansive coral reefs rich with marine life.', 'Beaches, Culture, Diving, Cuisine, History', 'Willemstad', 'Willemstad, Nieuwpoort, Barber, Sint Michiel', 'Dutch, Papiamento', 'Netherlands Antillean Guilder', 'https://e22hgs9rtwc.exactdn.com/wp-content/uploads/2021/11/shutterstock_2262892975.jpg?strip=all&lossy=1&ssl=1'),
(50, 'Cyprus', 'CY', 'An island country in the Eastern Mediterranean known for its rich history, archaeological sites, and beautiful beaches.', 'History, Beaches, Cuisine, Culture, Aphrodite', 'Nicosia', 'Nicosia, Limassol, Larnaca, Famagusta', 'Greek, Turkish', 'Euro', 'https://static.independent.co.uk/2024/03/12/11/iStock-689453204-2.jpg'),
(51, 'Czech Republic', 'CZ', 'A Central European country known for its ornate castles, medieval old towns, and native beers.', 'Prague, Castles, Beer, Culture, History', 'Prague', 'Prague, Brno, Ostrava, Plzeň', 'Czech', 'Czech Koruna', 'https://media.timeout.com/images/105836310/image.jpg'),
(52, 'Denmark', 'DK', 'A Scandinavian country comprising the Jutland Peninsula and numerous islands, known for its maritime history and modern design.', 'Hygge, Design, Vikings, Copenhagen, Islands', 'Copenhagen', 'Copenhagen, Aarhus, Odense, Aalborg', 'Danish', 'Danish Krone', 'https://imageio.forbes.com/specials-images/imageserve/64845748e7473b7e3c750fc7/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds'),
(53, 'Djibouti', 'DJ', 'A small country in the Horn of Africa known for its strategic location near the Bab-el-Mandeb Strait.', 'Desert, Sea, Culture, Geology, Hospitality', 'Djibouti City', 'Djibouti City, Ali Sabieh, Dikhil, Tadjourah', 'French, Arabic', 'Djiboutian Franc', 'https://www.state.gov/wp-content/uploads/2018/11/Djibouti-2498x1406.jpg'),
(54, 'Dominica', 'DM', 'An island country in the Caribbean with natural hot springs and tropical rainforests.', 'Nature, Hiking, Waterfalls, Culture, Volcanoes', 'Roseau', 'Roseau, Portsmouth, Marigot, Mahaut', 'English', 'Eastern Caribbean Dollar', 'https://media.voja.travel/wordpress/full/Uitzicht-op-Roseau---hoodstad-Dominica---Caribische-eilanden---vergezicht---stad---huizen---kleurrijk---water--kust---bootje.jpg'),
(55, 'Dominican Republic', 'DO', 'A Caribbean nation known for its beaches, resorts, and golfing.', 'Beaches, Merengue, Baseball, Culture, History', 'Santo Domingo', 'Santo Domingo, Santiago, La Romana, San Pedro de Macorís', 'Spanish', 'Dominican Peso', 'https://www.state.gov/wp-content/uploads/2023/07/shutterstock_1625847181v2.jpg'),
(56, 'Ecuador', 'EC', 'A country straddling the equator in northwestern South America, known for its diverse landscape and Galápagos Islands.', 'Galapagos, Andes, Amazon, Culture, Chocolate', 'Quito', 'Quito, Guayaquil, Cuenca, Santo Domingo de los Colorados', 'Spanish', 'US Dollar', 'https://www.state.gov/wp-content/uploads/2023/07/shutterstock_535492378v2.jpg'),
(57, 'Egypt', 'EG', 'A country linking northeast Africa with the Middle East, known for its pyramids and ancient civilization.', 'Pyramids, Nile, History, Culture, Sphinx', 'Cairo', 'Cairo, Alexandria, Giza, Shubra El-Kheima', 'Arabic', 'Egyptian Pound', 'https://facts.net/wp-content/uploads/2023/06/38-facts-about-egypt-1688101892.jpeg'),
(58, 'El Salvador', 'SV', 'A small Central American nation known for its Pacific Ocean beaches, surfing spots, and mountainous landscape.', 'Beaches, Volcanoes, Culture, History, Pupusas', 'San Salvador', 'San Salvador, Santa Ana, San Miguel, Soyapango', 'Spanish', 'US Dollar', 'https://reisexpert.b-cdn.net/wp-content/uploads/2020/12/Izalco-Vulkaan-Cerro-Verde-National-Park-El-Salvador.jpg'),
(59, 'Equatorial Guinea', 'GO', 'A Central African country comprising the Rio Muni mainland and 5 volcanic offshore islands.', 'Rainforest, Oil, Beaches, Culture, Wildlife', 'Malabo', 'Malabo, Bata, Ebebiyin, Aconibe', 'Spanish, French, Portuguese', 'Central African CFA franc', 'https://constructive-voices.com/wp-content/uploads/2024/04/Equatorial-Guinea-Sacred-Natural-Sites-and-Biodiversity.jpg'),
(60, 'Eritrea', 'ER', 'A country in the Horn of Africa known for its capital, Asmara, with Italian colonial architecture.', 'History, Culture, Red Sea, Hospitality, Cuisine', 'Asmara', 'Asmara, Massawa, Keren, Assab', 'Tigrinya, Arabic, English', 'Nakfa', 'https://i.pinimg.com/originals/37/47/d5/3747d5d0f1b87127ee651e6dfb0d719b.jpg'),
(61, 'Estonia', 'EE', 'A Baltic state in Northern Europe known for its diverse terrain of forests, beaches, and lakes.', 'Baltic, Tallinn, Nature, Culture, Technology', 'Tallinn', 'Tallinn, Tartu, Narva, Pärnu', 'Estonian', 'Euro', 'https://www.tallinnvoorbeginners.nl/wp-content/uploads/sites/7/2018/12/tallinnvoorbeginners-1000x572.jpg'),
(62, 'Ethiopia', 'ET', 'A country in the Horn of Africa known for its ancient culture, rich history, and dramatic landscapes.', 'History, Culture, Coffee, Nature, Wildlife', 'Addis Ababa', 'Addis Ababa, Dire Dawa, Mekelle, Gondar', 'Amharic', 'Ethiopian Birr', 'https://cdn1.matadornetwork.com/blogs/1/2021/01/Ethiopia-landscape-6.jpg'),
(63, 'Falkland Islands', 'FK', 'A British Overseas Territory in the South Atlantic Ocean, known for its rugged terrain and sheep farming.', 'Wildlife, Penguins, Nature, Islands, Hospitality', 'Stanley', 'Stanley', 'English', 'Falkland Islands Pound', 'https://eu-assets.simpleview-europe.com/falklandislands/imageresizer/?image=%2Fdbimgs%2FIMG_1979%20copy.jpeg&action=FeaturedItemsHeaderGallery3x2'),
(64, 'Faroe Islands', 'FO', 'An autonomous territory within the Kingdom of Denmark, known for its rugged cliffs, sea caves, and birdlife.', 'Nature, Sheep, Islands, Fishing, Culture', 'Tórshavn', 'Tórshavn, Klaksvík, Runavík, Tvøroyri', 'Faroese, Danish', 'Danish Krone', 'https://media.cntraveler.com/photos/6125bafe7dfe5dff926c770c/16:9/w_2580,c_limit/Faroe%20Kallur%20lighthouse%20GettyImages-1063834814.jpg'),
(65, 'Fiji', 'FJ', 'An archipelago of more than 300 islands in the South Pacific known for its rugged landscapes, palm-lined beaches, and coral reefs.', 'Islands, Beaches, Culture, Diving, Hospitality', 'Suva', 'Suva, Lautoka, Nadi, Labasa', 'English, Fijian, Hindi', 'Fijian Dollar', 'https://www.qantas.com/content/travelinsider/en/explore/south-pacific/fiji/things-to-know-before-you-go-to-fiji/_jcr_content/parsysTop/hero.img.full.medium.jpg/1706766618352.jpg'),
(66, 'Finland', 'FI', 'A Nordic country known for its vast forests, Arctic Lapland region, and numerous lakes.', 'Nature, Sauna, Aurora, Design, Lakes', 'Helsinki', 'Helsinki, Espoo, Tampere, Vantaa', 'Finnish, Swedish', 'Euro', 'https://cdn.outsideonline.com/wp-content/uploads/2023/03/finland-lead-h.jpg'),
(67, 'France', 'FR', 'A European country famous for its wines, cheeses, and iconic landmarks such as the Eiffel Tower and Louvre Museum.', 'Wine, Paris, Cuisine, Culture, Fashion', 'Paris', 'Paris, Marseille, Lyon, Toulouse', 'French', 'Euro', 'https://www.state.gov/wp-content/uploads/2023/07/shutterstock_667548661v2.jpg'),
(68, 'French Polynesia', 'PF', 'An overseas collectivity of France in the South Pacific, known for its coral reefs, overwater bungalows, and turquoise lagoons.', 'Islands, Beaches, Culture, Overwater, Hospitality', 'Papeete', 'Papeete, Faaa, Punaauia, Pirae', 'French, Tahitian', 'CFP Franc', 'https://www.discover-the-world.com/app/uploads/2020/04/french-polynesia-bora-bora-nui-aerial-view-astk-1800x0-c-default.jpg'),
(69, 'French West Indies', 'TF', 'A group of Caribbean islands that are overseas departments of France, known for their beaches and Creole culture.', 'Beaches, Culture, Cuisine, Islands, Paradise', 'Basse-Terre', 'Basse-Terre, Pointe-à-Pitre, Fort-de-France, Saint-Denis', 'French', 'Euro', 'https://s3.amazonaws.com/a-us.storyblok.com/f/1005231/85b118a743/st-barts_caribbean-southern_3504.jpg'),
(70, 'Gabon', 'GA', 'A country along the Atlantic coast of Central Africa known for its dense rainforests, diverse wildlife, and oil reserves.', 'Rainforest, Wildlife, Beaches, Culture, Oil', 'Libreville', 'Libreville, Port-Gentil, Franceville, Oyem', 'French', 'Central African CFA franc', 'https://nws.ams3.cdn.digitaloceanspaces.com/content/5A33D1474A94741A998AA72B8C722C9B/1292-2048.webp'),
(71, 'Gambia', 'GM', 'A West African country surrounded by Senegal known for its beaches, diverse ecosystems, and vibrant culture.', 'Beaches, Culture, Wildlife, Music, Hospitality', 'Banjul', 'Banjul, Serekunda, Brikama, Bakau', 'English', 'Gambian Dalasi', 'https://www.corendon.nl/inspiratie/wp-content/uploads/2015/07/waarom-gambia-blog.webp'),
(72, 'Georgia', 'GE', 'A country at the intersection of Europe and Asia known for its ancient wine-making tradition, mountain landscapes, and Black Sea coastline.', 'Caucasus, Wine, Cuisine, History, Hospitality', 'Tbilisi', 'Tbilisi, Kutaisi, Batumi, Rustavi', 'Georgian', 'Georgian Lari', 'https://storage.georgia.travel/images/tbilisi-picture.webp'),
(73, 'Germany', 'DE', 'A European country known for its rich cultural history, beer, and contributions to science and technology.', 'Beer, Castles, History, Culture, Efficiency', 'Berlin', 'Berlin, Hamburg, Munich, Cologne', 'German', 'Euro', 'https://images.ctfassets.net/wv75stsetqy3/1BdA9Yhg15SlIGHDXwpeR6/04399961d73af110aa29f1d6bedb8084/Germany_The_Pros_and_Cons_of_Living_in_Germany.jpg?q=60&fit=fill&fm=webp'),
(74, 'Ghana', 'GH', 'A West African country known for its rich history, diverse culture, and vibrant cities.', 'Culture, Cocoa, Hospitality, History, Music', 'Accra', 'Accra, Kumasi, Tamale, Sekondi-Takoradi', 'English', 'Ghanaian Cedi', 'https://mediaim.expedia.com/destination/1/be0ad25550296ffd601bb7d3dd6e3807.jpg'),
(75, 'Gibraltar', 'GI', 'A British Overseas Territory on Spain\'s south coast, known for its strategic location and iconic Rock of Gibraltar.', 'Rock, History, Monkeys, Views, Culture', 'Gibraltar City', 'Gibraltar City', 'English', 'Gibraltar Pound', 'https://www.andalusie.nl/wp-content/uploads/2022/04/waarom-is-gibraltar-brits.jpg'),
(76, 'Greece', 'GR', 'A country in southeastern Europe known for its ancient history, Mediterranean coastline, and picturesque islands.', 'History, Islands, Cuisine, Culture, Mythology', 'Athens', 'Athens, Thessaloniki, Patras, Heraklion', 'Greek', 'Euro', 'https://images.ctfassets.net/wv75stsetqy3/18jOEJrhKM7WA81nkCKZV8/6f70df258ed1233d5c3a8e3f01298b06/Greece.jpg?q=60&fit=fill&fm=webp'),
(77, 'Greenland', 'GL', 'An autonomous territory within the Kingdom of Denmark, known for its vast, ice-covered landmass.', 'Ice, Nature, Adventure, Inuit, Northern Lights', 'Nuuk', 'Nuuk, Sisimiut, Ilulissat, Qaqortoq', 'Greenlandic, Danish', 'Danish Krone', 'https://imageio.forbes.com/specials-images/imageserve/61a73e0ed5eec4787a298f7e/The-view-from-Hotel-Angmagssalik-over-the-frozen-fjord-in-Tasiilaq--Greenland-/960x0.jpg?format=jpg&width=960'),
(78, 'Grenada', 'GD', 'A Caribbean country known for its stunning beaches, spice plantations, and lush rainforests.', 'Spice, Beaches, Culture, Nutmeg, Hospitality', 'St. George\'s', 'St. George\'s, Gouyave, Grenville, Victoria', 'English', 'Eastern Caribbean Dollar', 'https://www.state.gov/wp-content/uploads/2019/04/Grenada-e1556100576970-2500x1406.jpg'),
(79, 'Guam', 'GU', 'An island territory of the United States in the western Pacific Ocean known for its beaches, World War II history, and Chamorro culture.', 'Beaches, Chamorro, Culture, US Territory, Hospitality', 'Hagåtña', 'Hagåtña, Dededo, Tamuning, Mangilao', 'English, Chamorro', 'United States Dollar', 'https://a.travel-assets.com/findyours-php/viewfinder/images/res70/51000/51605-Guam.jpg'),
(80, 'Guatemala', 'GT', 'A Central American country known for its Mayan history, volcanoes, and colonial architecture.', 'Mayan, Culture, Volcanoes, Cuisine, Textiles', 'Guatemala City', 'Guatemala City, Mixco, Villa Nueva, Quetzaltenango', 'Spanish', 'Quetzal', 'https://www.beyondtheordinary.co.uk/wp-content/uploads/2019/06/Guatemala-Holidays-Antigua-1600x1008.jpeg.webp'),
(81, 'Guernsey', 'GG', 'A British Crown dependency in the English Channel known for its picturesque landscapes, historic sites, and offshore finance industry.', 'Channel Islands, History, Culture, Beaches, Hospitality', 'St. Peter Port', 'St. Peter Port, St. Sampson, Vale, Castel', 'English, French', 'Guernsey Pound', 'https://www.imidaily.com/wp-content/uploads/2021/12/Guernsey.jpeg'),
(82, 'Guinea', 'GN', 'A West African country known for its rich natural resources, including bauxite and gold.', 'Culture, Beaches, Music, Hospitality, Diversity', 'Conakry', 'Conakry, N\'Zérékoré, Kankan, Kindia', 'French', 'Guinean Franc', 'https://i.pinimg.com/originals/08/e5/72/08e572b078efacbe56eb5aa1fbab7f66.jpg'),
(83, 'Guinea Bissau', 'GW', 'A West African country known for its tropical beaches, wildlife, and diverse ethnic groups.', 'Beaches, Culture, Wildlife, History, Hospitality', 'Bissau', 'Bissau, Bafatá, Gabú, Bissora', 'Portuguese', 'West African CFA franc', 'https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2014/01/guinea-bissau_and_the_bissagos_islands/13474677-1-eng-GB/Guinea-Bissau_and_the_Bissagos_islands_pillars.jpg'),
(84, 'Guyana', 'GY', 'A country on South America\'s North Atlantic coast known for its dense rainforests, diverse wildlife, and Kaieteur Falls.', 'Rainforest, Culture, Wildlife, Adventure, Hospitality', 'Georgetown', 'Georgetown, Linden, New Amsterdam, Anna Regina', 'English', 'Guyanese Dollar', 'https://worldlyadventurer.com/wp-content/uploads/2020/04/Guyana-Kaieteur-Falls-5.jpg'),
(85, 'Haiti', 'HT', 'A Caribbean country sharing the island of Hispaniola with the Dominican Republic, known for its vibrant culture and historical landmarks.', 'Culture, History, Music, Voodoo, Resilience', 'Port-au-Prince', 'Port-au-Prince, Carrefour, Delmas, Pétion-Ville', 'French, Haitian Creole', 'Haitian Gourde', 'https://a.travel-assets.com/findyours-php/viewfinder/images/res70/205000/205197-Haiti.jpg'),
(86, 'Honduras', 'HN', 'A Central American country known for its Caribbean and Pacific coastlines, Mayan ruins, and diverse wildlife.', 'Mayan, Beaches, Culture, Wildlife, Adventure', 'Tegucigalpa', 'Tegucigalpa, San Pedro Sula, Choloma, La Ceiba', 'Spanish', 'Honduran Lempira', 'https://merk.anwb.nl/transform/a9a687e1-7dfb-4de7-9047-c69c5236fd63/honduras_roatan_eiland_caribische-zee_getty?io=height%3A512%2Ctransform%3Afill%2Cwidth%3A3425'),
(87, 'Hong Kong', 'HK', 'A Special Administrative Region of China known for its skyline, deep natural harbor, and vibrant culture.', 'Skyline, Cuisine, Shopping, Culture, Efficiency', 'Victoria', 'Victoria', 'Cantonese, English', 'Hong Kong Dollar', 'https://static.333travel.nl/web-images/05/2019/5cda97925b13f/china-hong-kong-areal-small.jpeg'),
(88, 'Hungary', 'HU', 'A Central European country known for its rich history, thermal baths, and vibrant cultural scene.', 'History, Architecture, Cuisine, Thermal, Culture', 'Budapest', 'Budapest, Debrecen, Szeged, Miskolc', 'Hungarian', 'Hungarian Forint', 'https://www.state.gov/wp-content/uploads/2019/04/Hungary-2109x1406-2.jpg'),
(89, 'Iceland', 'IS', 'A Nordic island country known for its dramatic landscapes, including volcanoes, geysers, hot springs, and lava fields.', 'Nature, Aurora, Waterfalls, Geysers, Adventure', 'Reykjavik', 'Reykjavik, Kópavogur, Hafnarfjörður, Akureyri', 'Icelandic', 'Icelandic Króna', 'https://www.nationalgeographic.com/content/dam/expeditions/destinations/europe/land/Iceland-Volcanoes-Glaciers-Whales/hero-iceland-land-new-1.jpg'),
(90, 'India', 'IN', 'A vast South Asian country known for its diverse culture, rich history, and iconic landmarks such as the Taj Mahal.', 'Culture, Cuisine, History, Diversity, Spirituality', 'New Delhi', 'New Delhi, Mumbai, Bangalore, Kolkata', 'Hindi, English', 'Indian Rupee', 'https://www.asiadirect.nl/wp-content/uploads/2020/10/India-Agra-Taj-Mahal-1-scaled.jpg'),
(91, 'Indonesia', 'ID', 'A Southeast Asian archipelago known for its beaches, volcanoes, and vibrant cultures.', 'Islands, Culture, Cuisine, Wildlife, Diversity', 'Jakarta', 'Jakarta, Surabaya, Bandung, Medan', 'Indonesian', 'Indonesian Rupiah', 'https://facts.net/wp-content/uploads/2023/06/44-facts-about-indonesia-1688112759.jpeg'),
(92, 'Iran', 'IR', 'A country in Western Asia known for its ancient civilizations, Islamic architecture, and diverse landscapes.', 'History, Culture, Architecture, Cuisine, Hospitality', 'Tehran', 'Tehran, Mashhad, Isfahan, Tabriz', 'Persian', 'Iranian Rial', 'https://www.iransafar.co/wp-content/uploads/2021/images/Landscape/Laton-fall-Iran-Iransafar-Tours.jpg'),
(93, 'Iraq', 'IQ', 'A country in Western Asia known for its ancient Mesopotamian sites, including the city of Babylon.', 'History, Culture, Cuisine, Hospitality, Conflict', 'Baghdad', 'Baghdad, Mosul, Basra, Erbil', 'Arabic, Kurdish', 'Iraqi Dinar', 'https://socreatie.nl/wp-content/uploads/2021/01/20200518_164944-scaled.jpg'),
(94, 'Ireland', 'IE', 'An island in the North Atlantic known for its lush green landscapes, rich history, and vibrant pub culture.', 'Green, Guinness, History, Music, Literature', 'Dublin', 'Dublin, Cork, Galway, Limerick', 'Irish, English', 'Euro', 'https://images.ireland.com/thumbs/Images/amazing-landscapes/5079b776bd3645da95169ccd51f4278d/collagebackground-desktop.jpg'),
(95, 'Isle of Man', 'IM', 'A self-governing British Crown dependency in the Irish Sea known for its rugged coastline and medieval castles.', 'Celtic, TT Races, Culture, Heritage, Scenery', 'Douglas', 'Douglas, Ramsey, Peel, Castletown', 'English, Manx', 'Manx Pound', 'https://www.steam-packet.com/blog/wp-content/uploads/2019/10/123-1600x800.jpg'),
(96, 'Israel', 'IL', 'A country in the Middle East known for its historic landmarks, diverse culture, and religious significance.', 'History, Religion, Cuisine, Beaches, Innovation', 'Jerusalem', 'Jerusalem, Tel Aviv, Haifa, Beersheba', 'Hebrew, Arabic', 'Israeli New Shekel', 'https://i0.wp.com/www.touristisrael.com/wp-content/uploads/2013/12/Israel-Jordan-8-Day-Budget-Travel-Package-4.jpg?fit=800%2C373&ssl=1'),
(97, 'Italy', 'IT', 'A European country known for its rich history, art, architecture, and delicious cuisine.', 'Art, Cuisine, History, Fashion, Romance', 'Rome', 'Rome, Milan, Naples, Florence', 'Italian', 'Euro', 'https://delivery.gfobcontent.com/api/public/content/69158ae40b48417eb30d19fcc97942a8?v=160b28fd'),
(98, 'Jamaica', 'JM', 'A Caribbean island nation known for its stunning beaches, reggae music, and vibrant culture.', 'Reggae, Beaches, Cuisine, Culture, Hospitality', 'Kingston', 'Kingston, Montego Bay, Spanish Town, Portmore', 'English', 'Jamaican Dollar', 'https://i.natgeofe.com/k/053d2f8e-f28e-4e78-9680-fe35ed7b635d/jamaica-beach_16x9.jpg?w=1200'),
(99, 'Japan', 'JP', 'An East Asian country known for its advanced technology, rich culture, and beautiful landscapes.', 'Culture, Cuisine, Technology, Tradition, Nature', 'Tokyo', 'Tokyo, Osaka, Kyoto, Yokohama', 'Japanese', 'Japanese Yen', 'https://www.celebritycruises.com/blog/content/uploads/2021/03/what-is-japan-known-for-mt-fuji-hero-1920x890.jpg'),
(100, 'Jersey', 'JE', 'A British Crown dependency in the English Channel known for its beaches, historic sites, and offshore finance industry.', 'Channel Islands, History, Culture, Beaches, Hospitality', 'Saint Helier', 'Saint Helier, Saint Saviour, Saint Clement, Saint Lawrence', 'English, French', 'Jersey Pound', 'https://www.skr.de/fileadmin/_processed_/5/f/csm__de344d5433.jpg'),
(101, 'Jordan', 'JO', 'A country in the Middle East known for its ancient monuments, including Petra and the Dead Sea.', 'Petra, History, Culture, Overwatch, Hospitality', 'Amman', 'Amman, Zarqa, Irbid, Russeifa', 'Arabic', 'Jordanian Dinar', 'https://thenextcrossing.com/wp-content/uploads/2014/04/jordan_petra_the_monastery_1210-HDR-Pano-compressed.jpg'),
(102, 'Kazakhstan', 'KZ', 'A Central Asian country known for its vast steppe, mountains, and diverse cultural heritage.', 'Steppes, Culture, Hospitality, Nomads, Nature', 'Nur-Sultan', 'Nur-Sultan, Almaty, Shymkent, Karaganda', 'Kazakh, Russian', 'Kazakhstani Tenge', 'https://lp-cms-production.imgix.net/2023-03/kazakhstan-GettyImages-961506872-rfc.jpeg?auto=format&w=1920&h=640&fit=crop&crop=faces,edges&q=75'),
(103, 'Kenya', 'KE', 'An East African country known for its diverse wildlife, stunning landscapes, and vibrant culture.', 'Safari, Wildlife, Culture, Maasai, Beaches', 'Nairobi', 'Nairobi, Mombasa, Kisumu, Nakuru', 'Swahili, English', 'Kenyan Shilling', 'https://media.tacdn.com/media/attractions-content--1x-1/10/3d/cd/15.jpg'),
(104, 'Kiribati', 'KI', 'A Pacific island nation known for its remote location, coral atolls, and marine biodiversity.', 'Islands, Culture, Hospitality, Fishing, Atolls', 'South Tarawa', 'South Tarawa, Betio, Bairiki, Bikenibeu', 'English, Gilbertese', 'Australian Dollar', 'https://www.weer.nl/media/5oYzLxOIY38csnjuIkOglz/b27aad581f7299e3019563023139e549/South_Tarawa_from_the_air.jpg'),
(105, 'Kosovo', 'XK', 'A partially recognized state in Southeast Europe known for its cultural heritage and natural beauty.', 'History, Culture, Hospitality, Mountains, Independence', 'Pristina', 'Pristina, Prizren, Gjilan, Peć', 'Albanian, Serbian', 'Euro', 'https://www.nationsonline.org/gallery/Kosovo/Kosovo-Prizren-at-night.jpg'),
(106, 'Kuwait', 'KW', 'A country in Western Asia known for its oil reserves, modern architecture, and cultural heritage.', 'Oil, Skyscrapers, Hospitality, Cuisine, Culture', 'Kuwait City', 'Kuwait City, Al Ahmadi, Hawalli, Farwaniya', 'Arabic', 'Kuwaiti Dinar', 'https://content.r9cdn.net/rimg/dimg/97/e9/bbcce1e6-ctry-133-16cd86277ef.jpg?width=1366&height=768&xhint=1320&yhint=1420&crop=true'),
(107, 'Kyrgyzstan', 'KG', 'A Central Asian country known for its mountainous terrain, nomadic culture, and Silk Road history.', 'Mountains, Nomads, Culture, Hospitality, Adventure', 'Bishkek', 'Bishkek, Osh, Jalal-Abad, Karakol', 'Kyrgyz, Russian', 'Kyrgyzstani Som', 'https://facts.net/wp-content/uploads/2023/06/33-facts-about-kyrgyzstan-1688120619.jpg'),
(108, 'Laos', 'LA', 'A Southeast Asian country known for its mountainous terrain, Buddhist monasteries, and French colonial architecture.', 'Temples, Mountains, Culture, Waterfalls, Hospitality', 'Vientiane', 'Vientiane, Luang Prabang, Savannakhet, Pakse', 'Lao', 'Lao Kip', 'https://www.state.gov/wp-content/uploads/2023/07/shutterstock_2186136317v2.jpg'),
(109, 'Latvia', 'LV', 'A Baltic country in Northern Europe known for its forests, beaches, and medieval Old Towns.', 'Baltic, Riga, Culture, Nature, History', 'Riga', 'Riga, Daugavpils, Liepāja, Jelgava', 'Latvian', 'Euro', 'https://lp-cms-production.imgix.net/2023-03/latvia-GettyImages-516021467-rfc.jpeg?auto=format&w=1920&h=640&fit=crop&crop=faces,edges&q=75'),
(110, 'Lebanon', 'LB', 'A country in the Middle East known for its ancient ruins, vibrant cities, and diverse culture.', 'History, Cuisine, Culture, Hospitality, Mountains', 'Beirut', 'Beirut, Tripoli, Sidon, Tyre', 'Arabic', 'Lebanese Pound', 'https://lp-cms-production.imgix.net/2019-06/eced05b8f4e21a3bff2a2d92143412d7-lebanon.jpg?auto=format&w=1920&h=640&fit=crop&crop=faces,edges&q=75'),
(111, 'Lesotho', 'LS', 'A small, landlocked country in Southern Africa known for its mountainous terrain and traditional culture.', 'Mountains, Culture, Adventure, Hospitality, Basotho', 'Maseru', 'Maseru, Teyateyaneng, Mafeteng, Hlotse', 'English, Sesotho', 'Lesotho Loti', 'https://media-01.imu.nl/storage/exclusiveculitravel.nl/10029/lesotho-1920x500.jpg'),
(112, 'Liberia', 'LR', 'A country on the West African coast known for its lush rainforests, diverse wildlife, and troubled history.', 'Rainforest, Culture, Wildlife, Hospitality, Beaches', 'Monrovia', 'Monrovia, Gbarnga, Kakata, Bensonville', 'English', 'Liberian Dollar', 'https://www.idhsustainabletrade.com/uploaded/2017/01/South-East-Landscape-Liberia-e1524647657161-1440x450-c-default.jpg?x63550&x63550'),
(113, 'Libya', 'LY', 'A North African country known for its Sahara Desert landscapes, ancient ruins, and Mediterranean coastline.', 'Desert, History, Culture, Hospitality, Conflict', 'Tripoli', 'Tripoli, Benghazi, Misrata, Tarhuna', 'Arabic', 'Libyan Dinar', 'https://i.natgeofe.com/k/78c322ca-f4b0-433c-8273-3652cdd7a457/libya-tripoli_2x1.jpg'),
(114, 'Liechtenstein', 'LI', 'A small, landlocked country in Central Europe known for its alpine landscapes and low taxes.', 'Alps, Microstate, Scenery, Culture, Banking', 'Vaduz', 'Vaduz, Schaan, Triesen, Balzers', 'German', 'Swiss Franc', 'https://lp-cms-production.imgix.net/2019-06/55946484.jpg?auto=format&w=1920&h=640&fit=crop&crop=faces,edges&q=75'),
(115, 'Lithuania', 'LT', 'A Baltic country in Northern Europe known for its medieval towns, castles, and lush forests.', 'Baltic, Vilnius, Culture, Nature, History', 'Vilnius', 'Vilnius, Kaunas, Klaipėda, Šiauliai', 'Lithuanian', 'Euro', 'https://media.nomadicmatt.com/2020/lithuaniaguide1.jpg');
INSERT INTO `traveladvice` (`countryID`, `countryName`, `countryCode`, `countryDescription`, `countryKeywords`, `countryCapital`, `countryMajorCities`, `countryLanguages`, `countryCurrency`, `countryImage`) VALUES
(116, 'Luxembourg', 'LU', 'A small European country known for its medieval castles, rolling countryside, and high standard of living.', 'Castles, Banking, Nature, Culture, Multilingual', 'Luxembourg City', 'Luxembourg City, Esch-sur-Alzette, Dudelange, Differdange', 'Luxembourgish, French, German', 'Euro', 'https://www.sprachcaffe.com/fileadmin/_processed_/6/3/csm_Luxembourg_Header_64863f7e59.png'),
(117, 'Macau', 'MO', 'A Special Administrative Region of China known for its vibrant casinos, Portuguese colonial history, and fusion cuisine.', 'Casinos, Culture, Cuisine, History, Entertainment', 'Macau City', 'Macau City', 'Cantonese, Portuguese', 'Macanese Pataca', 'https://media.tacdn.com/media/attractions-content--1x-1/10/5a/89/3a.jpg'),
(118, 'Macedonia', 'MK', 'A country in the Balkans known for its diverse culture, historic sites, and scenic landscapes.', 'History, Culture, Nature, Hospitality, Lakes', 'Skopje', 'Skopje, Bitola, Kumanovo, Prilep', 'Macedonian', 'Macedonian Denar', 'https://www.holidayhypermarket.co.uk/wp-content/uploads/2023/01/HH_North_Macedonia_shutterstock_1476848549.png'),
(119, 'Madagascar', 'MG', 'An island nation in the Indian Ocean known for its unique wildlife, lush rainforests, and beautiful beaches.', 'Wildlife, Lemurs, Baobabs, Nature, Culture', 'Antananarivo', 'Antananarivo, Toamasina, Antsirabe, Fianarantsoa', 'Malagasy, French', 'Malagasy Ariary', 'https://oryxtravel.nl/wp-content/uploads/2020/05/shutterstock_1125367931-scaled.jpg'),
(120, 'Malawi', 'MW', 'A landlocked country in southeastern Africa known for its scenic landscapes, including Lake Malawi.', 'Lake Malawi, Wildlife, Culture, Scenery, Hospitality', 'Lilongwe', 'Lilongwe, Blantyre, Mzuzu, Zomba', 'English, Chewa', 'Malawian Kwacha', 'https://i0.wp.com/www.atelier-africa.com/wp-content/uploads/2018/02/Malawi-Alma-Travel.jpg?fit=1475%2C860&ssl=1'),
(121, 'Malaysia', 'MY', 'A Southeast Asian country known for its diverse culture, stunning beaches, and modern cities.', 'Diverse, Cuisine, Culture, Nature, Islands', 'Kuala Lumpur', 'Kuala Lumpur, George Town, Ipoh, Johor Bahru', 'Malay', 'Malaysian Ringgit', 'https://www.gecf.org/_resources/files/locations/malaysia/malaysia-2.png'),
(122, 'Maldives', 'MV', 'An Indian Ocean archipelago known for its luxury resorts, turquoise waters, and vibrant marine life.', 'Beaches, Resorts, Diving, Luxury, Paradise', 'Malé', 'Malé', 'Dhivehi', 'Maldivian Rufiyaa', 'https://www.authenticindiatours.com/app/uploads/2022/05/10-facts-about-the-Maldives-1400x550-c-default.jpg'),
(123, 'Mali', 'ML', 'A landlocked country in West Africa known for its historic cities, Sahara Desert, and diverse culture.', 'Culture, History, Music, Sahara, Hospitality', 'Bamako', 'Bamako, Sikasso, Mopti, Segou', 'French', 'West African CFA franc', 'https://www.nationsonline.org/gallery/Mali/Great-Mosque-Djenne-Mali.jpg'),
(124, 'Malta', 'MT', 'A Southern European island nation known for its historic sites, crystal-clear waters, and Mediterranean cuisine.', 'History, Culture, Beaches, Cuisine, Hospitality', 'Valletta', 'Valletta, Birkirkara, Mosta, Qormi', 'Maltese, English', 'Euro', 'https://internationalliving.com/_next/image/?url=https%3A%2F%2Fimages.ctfassets.net%2Fwv75stsetqy3%2F7rTzoyS6NbT9DUhSyb2F9E%2F7b2e47b65e3a5a06f6c3b236b442947b%2FMalta.jpg%3Fq%3D60%26fit%3Dfill%26fm%3Dwebp&w=3840&q=60'),
(125, 'Marshall Islands', 'MH', 'A Pacific island country known for its stunning coral reefs, World War II history, and traditional culture.', 'Islands, Culture, Fishing, Hospitality, Atolls', 'Majuro', 'Majuro, Ebeye, Jabor, Wotje', 'Marshallese, English', 'United States Dollar', 'https://res.cloudinary.com/dail4fbms/image/upload/c_limit,w_1366/f_auto/q_auto/v1636552645/marshall_islands_bikini_atol_large_aaa8418231?_a=BAVAqQIB0'),
(126, 'Mauritania', 'MR', 'A country in West Africa known for its Sahara Desert landscapes, ancient caravan routes, and diverse ethnic groups.', 'Desert, Culture, Hospitality, History, Islam', 'Nouakchott', 'Nouakchott, Nouadhibou, Kaédi, Rosso', 'Arabic', 'Mauritanian Ouguiya', 'https://intro.africa/wp-content/uploads/2020/06/Mauritania4.jpg'),
(127, 'Mauritius', 'MU', 'An island nation in the Indian Ocean known for its stunning beaches, coral reefs, and multicultural society.', 'Beaches, Culture, Cuisine, Hospitality, Romance', 'Port Louis', 'Port Louis, Beau Bassin-Rose Hill, Vacoas-Phoenix, Curepipe', 'Mauritian Creole, French, English', 'Mauritian Rupee', 'https://a.loveholidays.com/media-library/~production/6c9ff0a36bda067fb1e9a462b8cf0fab5afc72f5-3840x1408.jpg?auto=avif%2Cwebp&quality=80&dpr=1.5&optimize=high&fit=crop&width=1280&height=380'),
(128, 'Mexico', 'MX', 'A country in North America known for its rich cultural heritage, delicious cuisine, and diverse landscapes.', 'Culture, Cuisine, Beaches, History, Mayan', 'Mexico City', 'Mexico City, Guadalajara, Monterrey, Puebla', 'Spanish', 'Mexican Peso', 'https://static.333travel.nl/web-images/07/2020/5f15ac3042f34/mexico-mexico-stad-panorama-teotihuacan-piramides-van-de-zon-en-maan.jpeg'),
(129, 'Micronesia', 'FM', 'A country in the western Pacific Ocean known for its many small islands, coral reefs, and World War II history.', 'Islands, Culture, Hospitality, Fishing, Diving', 'Palikir', 'Palikir, Weno, Kolonia, Tofol', 'English', 'United States Dollar', 'https://www.micronesiatour.com/sites/default/files/micronesia-islands-tour-travel-vacation-diving-photos-PALAU.jpg'),
(130, 'Moldova', 'MD', 'A landlocked country in Eastern Europe known for its wine culture, historic sites, and rural landscapes.', 'Wine, Culture, Hospitality, History, Countryside', 'Chisinau', 'Chisinau, Tiraspol, Balti, Bender', 'Moldovan', 'Moldovan Leu', 'https://www.nationsonline.org/gallery/Moldova/Old-Orhei-Moldova.jpg'),
(131, 'Monaco', 'MC', 'A small city-state on the French Riviera known for its glamorous casinos, yacht-lined harbor, and Formula One Grand Prix.', 'Casinos, Luxury, Yachts, F1, Wealth', 'Monaco City', 'Monaco City', 'French', 'Euro', 'https://media.tacdn.com/media/attractions-content--1x-1/10/6e/96/28.jpg'),
(132, 'Mongolia', 'MN', 'A landlocked country in East Asia known for its vast steppes, nomadic culture, and Genghis Khan\'s empire history.', 'Nomads, Steppes, Culture, Hospitality, Adventure', 'Ulaanbaatar', 'Ulaanbaatar, Erdenet, Darkhan, Choibalsan', 'Mongolian', 'Mongolian Tugrik', 'https://media.tacdn.com/media/attractions-content--1x-1/11/ec/01/a2.jpg'),
(133, 'Montenegro', 'ME', 'A country in southeastern Europe known for its rugged mountains, medieval villages, and Adriatic coastline.', 'Coastline, Mountains, Culture, Hospitality, History', 'Podgorica', 'Podgorica, Nikšić, Herceg Novi, Pljevlja', 'Montenegrin', 'Euro', 'https://www.oliverstravels.com/blog/wp-content/uploads/2019/08/Montenegro.jpg'),
(134, 'Montserrat', 'MS', 'A British Overseas Territory in the Caribbean known for its volcanic landscapes, beaches, and diving spots.', 'Volcano, Beaches, Nature, Hospitality, Culture', 'Plymouth', 'Plymouth, Brades, Saint Peter\'s, Salem', 'English', 'Eastern Caribbean Dollar', 'https://www.spain.info/.content/imagenes/cabeceras-grandes/cataluna/monasterio_montserrat_s_628801775.jpg'),
(135, 'Morocco', 'MA', 'A North African country known for its vibrant cities, historic medinas, and diverse landscapes, including the Sahara Desert.', 'Culture, Cuisine, Medina, Mountains, Desert', 'Rabat', 'Rabat, Casablanca, Marrakech, Fez', 'Arabic, Berber', 'Moroccan Dirham', 'https://media.nomadicmatt.com/moroccoguide.jpg'),
(136, 'Mozambique', 'MZ', 'A country in southeastern Africa known for its stunning beaches, coral reefs, and wildlife reserves.', 'Beaches, Wildlife, Culture, Hospitality, Islands', 'Maputo', 'Maputo, Matola, Beira, Nampula', 'Portuguese', 'Mozambican Metical', 'https://artofsafari.travel/wp-content/uploads/2017/09/BANNER_Stock_Mozambique_Quirimbas_JustinFox.jpg'),
(137, 'Myanmar', 'MM', 'A Southeast Asian country known for its ancient temples, diverse cultures, and scenic landscapes.', 'Temples, Culture, Cuisine, Hospitality, Nature', 'Naypyidaw', 'Naypyidaw, Yangon, Mandalay, Bagan', 'Burmese', 'Burmese Kyat', 'https://lp-cms-production.imgix.net/2019-06/b940a3bed4852b6e1a5177fc7d09b5fa8eed81c1ca637d1a94f95e9de0e2649f.jpg?auto=format&w=1920&h=640&fit=crop&crop=faces,edges&q=75'),
(138, 'Namibia', 'NA', 'A country in southern Africa known for its vast desert landscapes, wildlife reserves, and indigenous cultures.', 'Desert, Wildlife, Culture, Adventure, Hospitality', 'Windhoek', 'Windhoek, Rundu, Walvis Bay, Oshakati', 'English, Afrikaans', 'Namibian Dollar', 'https://www.abercrombiekent.co.uk/-/media/abercrombieandkent/images/page-header-images/africa/namibia/namibia_0001_namibia-tree-desert-shutterstock_5961298.jpg?w=1920&h=940'),
(139, 'Nauru', 'NR', 'A small island country in the Pacific Ocean known for its phosphate mining industry and remote location.', 'Island, Phosphate, Pacific, Hospitality, Culture', 'Yaren', 'Yaren', 'Nauruan, English', 'Australian Dollar', 'https://facts.net/wp-content/uploads/2023/07/30-facts-about-nauru-1688192153.jpeg'),
(140, 'Nepal', 'NP', 'A landlocked country in South Asia known for its Himalayan mountains, ancient temples, and diverse culture.', 'Himalayas, Trekking, Culture, Hospitality, Adventure', 'Kathmandu', 'Kathmandu, Pokhara, Lalitpur, Bharatpur', 'Nepali', 'Nepalese Rupee', 'https://triplegend.com/wp-content/uploads/2022/02/Nepal-Himalaya-Glacier-Lake-I-James-Chou-scaled.jpg.webp'),
(141, 'Netherlands', 'NL', 'A European country known for its flat landscape, picturesque canals, windmills, and vibrant tulip fields.', 'Windmills, Tulips, King\'s Day, Cycling, Canals', 'Amsterdam', 'Amsterdam, Rotterdam, The Hague, Eindhoven, Helmond', 'Dutch, Frisian, Streetlanguage, Limburgs (aka german With a beroerte),  Too many Foreign Languages', 'Euro', 'https://s30876.pcdn.co/wp-content/uploads/Netherlands3-e1634207438966.jpg.optimal.jpg'),
(142, 'Netherlands Antilles', 'AN', 'A former Dutch colony in the Caribbean known for its tropical beaches, diving spots, and vibrant culture.', 'Beaches, Culture, Cuisine, Islands, Scuba', 'Willemstad', 'Willemstad, Kralendijk, Oranjestad, Philipsburg', 'Dutch, English, Papiamento', 'Netherlands Antillean Guilder', 'https://images.scubago.com/live-scubago-images/landingpageimages/2020-01-09/20200109T093126596.jpeg'),
(143, 'New Caledonia', 'NC', 'A French territory in the Pacific Ocean known for its stunning lagoons, coral reefs, and Melanesian culture.', 'Islands, Coral, Culture, Hospitality, French', 'Noumea', 'Noumea, Mont-Dore, Dumbéa, Païta', 'French', 'CFP Franc', 'https://lp-cms-production.imgix.net/2019-06/70745365.jpg?auto=format&w=1920&h=640&fit=crop&crop=faces,edges&q=75'),
(144, 'New Zealand', 'NZ', 'A country in the southwestern Pacific Ocean known for its breathtaking landscapes, Maori culture, and outdoor activities.', 'Nature, Adventure, Maori, Culture, Hospitality', 'Wellington', 'Wellington, Auckland, Christchurch, Hamilton', 'English, Maori', 'New Zealand Dollar', 'https://www.abercrombiekent.com/-/media/ak/media-for-prod/destinations/mastheads/new-zealand-mount-cook-mh.jpg?h=660&w=1920&la=en&hash=590C607A115CA81A12BA2B3301E0EB5F'),
(145, 'Nicaragua', 'NI', 'A country in Central America known for its stunning beaches, volcanic landscapes, and colonial architecture.', 'Volcanoes, Lakes, Beaches, Culture, Hospitality', 'Managua', 'Managua, León, Granada, Masaya', 'Spanish', 'Nicaraguan Córdoba', 'https://images.ctfassets.net/wv75stsetqy3/nTUu9cLUUZvuBpngqDpXR/7737e88e1d639a009a097aad6c4392bd/Nicaragua.jpg?q=60&fit=fill&fm=webp'),
(146, 'Niger', 'NE', 'A landlocked country in West Africa known for its Saharan landscapes, diverse wildlife, and traditional cultures.', 'Desert, Culture, Wildlife, Hospitality, Music', 'Niamey', 'Niamey, Zinder, Maradi, Agadez', 'French', 'West African CFA franc', 'https://www.nationsonline.org/gallery/Niger/Panorama-of-Bouza-Dosso.jpg'),
(147, 'Nigeria', 'NG', 'A country in West Africa known for its diverse culture, bustling cities, and natural landmarks like Zuma Rock and Yankari National Park.', 'Culture, Cuisine, Music, Nollywood, Hospitality', 'Abuja', 'Abuja, Lagos, Kano, Ibadan', 'English', 'Nigerian Naira', 'https://peakvisor.com/photo/nigeria.jpg'),
(148, 'Norway', 'NO', 'A Scandinavian country known for its stunning fjords, northern lights, and high quality of life.', 'Fjords, Nature, Aurora, Adventure, Hospitality', 'Oslo', 'Oslo, Bergen, Trondheim, Stavanger', 'Norwegian', 'Norwegian Krone', 'https://media.tacdn.com/media/attractions-content--1x-1/0b/de/5c/17.jpg'),
(149, 'Oman', 'OM', 'A country on the southeastern coast of the Arabian Peninsula known for its desert landscapes, historic forts, and rich culture.', 'Desert, Culture, Hospitality, Mountains, Coastline', 'Muscat', 'Muscat, Salalah, Sohar, Nizwa', 'Arabic', 'Omani Rial', 'https://media.audleytravel.com/-/media/images/home/north-africa-and-the-middle-east/oman/country-guides/a-guide-to-visiting-oman-for-the-first-time/istock_861935418_muscat_8007889_letterbox.jpg?q=79&w=1920&h=640'),
(150, 'Pakistan', 'PK', 'A country in South Asia known for its diverse landscapes, rich history, and cultural heritage, including the ancient city of Mohenjo-daro.', 'Culture, Mountains, History, Hospitality, Cuisine', 'Islamabad', 'Islamabad, Karachi, Lahore, Faisalabad', 'Urdu, English', 'Pakistani Rupee', 'https://lp-cms-production.imgix.net/2019-06/91992443%20.jpg?auto=format&w=1920&h=640&fit=crop&crop=faces,edges&q=75'),
(151, 'Palau', 'PW', 'A country in the western Pacific Ocean known for its pristine beaches, vibrant coral reefs, and World War II history.', 'Islands, Diving, Culture, Hospitality, Nature', 'Ngerulmud', 'Ngerulmud, Koror, Meyungs, Airai', 'Palauan, English', 'United States Dollar', 'https://lp-cms-production.imgix.net/2019-06/76943aaaf851cc56846df99114176057-palau.jpg?auto=format&w=1920&h=640&fit=crop&crop=faces,edges&q=75'),
(152, 'Palestine', 'PS', 'A region in the Middle East known for its historical significance, including Jerusalem, and ongoing geopolitical tensions.', 'History, Culture, Conflict, Hospitality, Cuisine', 'Ramallah', 'Ramallah, Gaza City, Hebron, Nablus', 'Arabic', 'Israeli Shekel', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/ce1a307b-4fab-4cab-8a17-93aa44e6e8f9/de064v9-471d9c87-6d43-491d-9e60-b53e73c88ad8.jpg/v1/fill/w_1024,h_538,q_75,strp/countryside___palestine_by_eyadstudio_de064v9-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTM4IiwicGF0aCI6IlwvZlwvY2UxYTMwN2ItNGZhYi00Y2FiLThhMTctOTNhYTQ0ZTZlOGY5XC9kZTA2NHY5LTQ3MWQ5Yzg3LTZkNDMtNDkxZC05ZTYwLWI1M2U3M2M4OGFkOC5qcGciLCJ3aWR0aCI6Ijw9MTAyNCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.JNypIAn3tYGY3nILkRk8WQNxzyzDKrgdwMP6symszXw'),
(153, 'Panama', 'PA', 'A country in Central America known for its famous canal, diverse wildlife, and vibrant culture.', 'Canal, Culture, Beaches, Hospitality, Wildlife', 'Panama City', 'Panama City, San Miguelito, David, La Chorrera', 'Spanish', 'Panamanian Balboa, United States Dollar', 'https://lp-cms-production.imgix.net/2022-12/iStock-1264005950.jpg?auto=format&w=1920&h=640&fit=crop&crop=faces,edges&q=75'),
(154, 'Papua New Guinea', 'PG', 'A country in the southwestern Pacific known for its diverse culture, tropical rainforests, and coral reefs.', 'Culture, Wildlife, Adventure, Hospitality, Islands', 'Port Moresby', 'Port Moresby, Lae, Mount Hagen, Madang', 'English, Tok Pisin, Hiri Motu', 'Papua New Guinean Kina', 'https://www.aqua-firma.com/contentFiles/image/papua-new-guinea/milne-bay-papua-new-guinea-dive-diving-resort-snorkelling-coral-reef-tropical-rainforest-travel-vacation-holiday-tawali-bird-watching-alotau-manta-ray4.jpg'),
(155, 'Paraguay', 'PY', 'A landlocked country in South America known for its Guarani culture, Jesuit missions, and lush landscapes.', 'Culture, Wildlife, Jesuit, Hospitality, Guarani', 'Asunción', 'Asunción, Ciudad del Este, San Lorenzo, Luque', 'Spanish, Guarani', 'Paraguayan Guarani', 'https://thegeep.org/sites/default/files/styles/subpage_banner_wide/public/2019-04/Salto_cristal_-_yvykui_-_paraguay_-_2005-04-23.jpg?h=6eb229a4&itok=QPz5MNO7'),
(156, 'Peru', 'PE', 'A country in western South America known for its ancient Inca ruins, Amazon rainforest, and vibrant Andean culture.', 'Inca, Machu Picchu, Cuisine, Culture, Adventure', 'Lima', 'Lima, Arequipa, Trujillo, Chiclayo', 'Spanish, Quechua, Aymara', 'Peruvian Sol', 'https://media.tacdn.com/media/attractions-content--1x-1/0b/de/a9/2d.jpg'),
(157, 'Philippines', 'PH', 'An archipelago in Southeast Asia known for its stunning beaches, vibrant cities, and rich cultural heritage.', 'Islands, Beaches, Cuisine, Hospitality, Culture', 'Manila', 'Manila, Quezon City, Davao City, Cebu City', 'Filipino, English', 'Philippine Peso', 'https://imageio.forbes.com/specials-images/imageserve/662156675cc14bdea9a2f524/header/0x0.jpg?format=jpg&height=1278&width=2520'),
(158, 'Poland', 'PL', 'A country in Central Europe known for its medieval architecture, historic cities, and rich cultural heritage.', 'History, Culture, Cuisine, Hospitality, Solidarity', 'Warsaw', 'Warsaw, Kraków, Łódź, Wrocław', 'Polish', 'Polish Złoty', 'https://www.usnews.com/object/image/0000015a-397b-d9e9-a9da-bf7fed970000/bc17-poland-crop.jpg?update-time=1487098372148&size=superhero-large'),
(159, 'Portugal', 'PT', 'A country in Southern Europe known for its historic cities, beautiful beaches, and delicious cuisine, including pastéis de nata.', 'History, Culture, Cuisine, Beaches, Hospitality', 'Lisbon', 'Lisbon, Porto, Vila Nova de Gaia, Amadora', 'Portuguese', 'Euro', 'https://magazine.secretescapes.se/wp-content/uploads/2021/05/adfdd-istock-533693479-1-new-banner.jpg'),
(160, 'Puerto Rico', 'PR', 'A Caribbean island territory of the United States known for its tropical beaches, vibrant culture, and historic forts.', 'Beaches, Culture, Cuisine, Music, Hospitality', 'San Juan', 'San Juan, Bayamón, Carolina, Ponce', 'Spanish, English', 'United States Dollar', 'https://i.natgeofe.com/k/432cb4c5-6c31-4c95-bd1c-65765aae5356/san_juan_2x1.jpg'),
(161, 'Qatar', 'QA', 'A country on the Arabian Peninsula known for its futuristic skyscrapers, luxury shopping, and vast desert landscapes.', 'Oil, Skyscrapers, Culture, Desert, Luxury', 'Doha', 'Doha, Al Rayyan, Umm Salal, Al Wakrah', 'Arabic', 'Qatari Riyal', 'https://www.civitatis.com/blog/wp-content/uploads/2022/11/doha-panoramica-1920x540.jpg'),
(162, 'Reunion', 'RE', 'A French overseas department in the Indian Ocean known for its volcanic landscapes, coral reefs, and Creole culture.', 'Volcanoes, Beaches, Culture, Hiking, Hospitality', 'Saint-Denis', 'Saint-Denis, Saint-Paul, Saint-Pierre, Le Tampon', 'French', 'Euro', 'https://guide.en-vols.com/wp-content/uploads/aftg/2022/02/metaIDnameCITY-RUN-1-2.jpg'),
(163, 'Romania', 'RO', 'A country in Eastern Europe known for its medieval castles, lush forests, and vibrant folk traditions.', 'Castles, Dracula, Culture, History, Carpathians', 'Bucharest', 'Bucharest, Cluj-Napoca, Timișoara, Iași', 'Romanian', 'Romanian Leu', 'https://www.coxandkings.co.uk/-/media/cox-and-kings/images/tours/destinations/europe/romania/timeless-romania/header-timeless-romania.jpg?la=en&hash=6ADC844DB1DC2B6D40A318A798042432C34EA374'),
(164, 'Russia', 'RU', 'The largest country in the world, stretching from Eastern Europe to Northern Asia, known for its rich history, diverse culture, and vast landscapes.', 'Size, History, Culture, Vodka, Architecture', 'Moscow', 'Moscow, Saint Petersburg, Novosibirsk, Yekaterinburg', 'Russian', 'Russian Ruble', 'https://lp-cms-production.imgix.net/2023-03/500pxRF_61786861.jpg'),
(165, 'Rwanda', 'RW', 'A landlocked country in East Africa known for its stunning scenery, including volcanoes and lakes, and its remarkable recovery from the 1994 genocide.', 'Gorillas, Wildlife, Culture, Hills, Recovery', 'Kigali', 'Kigali, Butare, Gitarama, Ruhengeri', 'Kinyarwanda, English, French', 'Rwandan Franc', 'https://media.snl.no/media/187066/article_topimage_rwanda.jpg'),
(166, 'Saint Pierre & Miquelon', 'PM', 'A French overseas collectivity in North America consisting of several islands known for their fishing industry, rugged coastlines, and French culture.', 'French, Islands, Fishing, Culture, History', 'Saint-Pierre', 'Saint-Pierre', 'French', 'Euro', 'https://www.spm-tourisme.fr/app/uploads/saintpierreetmiquelon/2022/11/thumbs/MD_SPM_SP_H_Oct2018-108-1-1920x960.jpg'),
(167, 'Samoa', 'WS', 'A country in the South Pacific known for its stunning beaches, lush rainforests, and vibrant Polynesian culture.', 'Islands, Culture, Hospitality, Beaches, Traditions', 'Apia', 'Apia, Vaitele, Faleula, Salelologa', 'Samoan, English', 'Samoan Tala', 'https://samoa.travel//Content/SiteResources/PAGE/580/0a1e55bf-d950-40e3-875e-94fb7fc559bc/inland-swimming-holes-new.jpg'),
(168, 'San Marino', 'SM', 'A microstate surrounded by Italy known for its medieval architecture, scenic landscapes, and low tax rates.', 'Microstate, History, Culture, Medieval, Scenery', 'City of San Marino', 'City of San Marino', 'Italian', 'Euro', 'https://lp-cms-production.imgix.net/2019-06/89378017%20.jpg?auto=format&w=1920&h=640&fit=crop&crop=faces,edges&q=75'),
(169, 'Sao Tome and Principe', 'ST', 'An island nation in the Gulf of Guinea known for its lush rainforests, beautiful beaches, and Portuguese colonial heritage.', 'Islands, Nature, Culture, Cocoa, Hospitality', 'Sao Tome', 'Sao Tome, Santo António, Neves, Santana', 'Portuguese', 'Sao Tome and Principe Dobra', 'https://www.muchbetteradventures.com/magazine/content/images/2023/06/sao-tome-galapagps.jpg'),
(170, 'Saudi Arabia', 'SA', 'A country in the Middle East known for its vast deserts, rich history, and Islamic heritage, including the cities of Mecca and Medina.', 'Oil, Desert, Mecca, Culture, Skyscrapers', 'Riyadh', 'Riyadh, Jeddah, Mecca, Medina', 'Arabic', 'Saudi Riyal', 'https://www.state.gov/wp-content/uploads/2023/07/shutterstock_1938189982v2.jpg'),
(171, 'Senegal', 'SN', 'A country in West Africa known for its vibrant culture, bustling markets, and beautiful beaches along the Atlantic coast.', 'Music, Culture, Beaches, Hospitality, History', 'Dakar', 'Dakar, Touba, Thies, Rufisque', 'French', 'West African CFA franc', 'https://media.tidesoftware.be/media/10/Products/Afrika/Senegal/shutterstock_1284152605.jpg?crop=0%2C0%2C0%2C0&cropmode=percentage&width=1920&mode=max'),
(172, 'Serbia', 'RS', 'A landlocked country in Southeast Europe known for its rich history, vibrant culture, and stunning Orthodox monasteries.', 'History, Culture, Music, Hospitality, Belgrade', 'Belgrade', 'Belgrade, Novi Sad, Niš, Kragujevac', 'Serbian', 'Serbian Dinar', 'https://www.outlooktravelmag.com/media/serbia-1-1670597443.profileImage.2x-jpg.webp'),
(173, 'Seychelles', 'SC', 'An archipelago in the Indian Ocean known for its pristine beaches, coral reefs, and luxurious resorts.', 'Beaches, Islands, Nature, Luxury, Hospitality', 'Victoria', 'Victoria', 'Seychellois Creole, English, French', 'Seychellois Rupee', 'https://admin.seychelles.com/sites/default/files/2024-01/About_Seychelles.jpg'),
(174, 'Sierra Leone', 'SL', 'A country in West Africa known for its stunning beaches, diverse wildlife, and vibrant culture.', 'Beaches, Culture, Diamonds, Wildlife, Recovery', 'Freetown', 'Freetown, Bo, Kenema, Koidu', 'English', 'Sierra Leonean Leone', 'https://hips.hearstapps.com/hmg-prod/images/sierra-leone-travel-destination-04-1499872428.jpg'),
(175, 'Singapore', 'SG', 'A city-state and island country in Southeast Asia known for its modern skyline, multicultural society, and efficient public transport.', 'Skyscrapers, Cuisine, Culture, Efficiency, Shopping', 'Singapore City', 'Singapore City', 'English, Malay, Mandarin, Tamil', 'Singapore Dollar', 'https://i0.wp.com/cdn.tiqets.com/wordpress/blog/wp-content/uploads/2020/09/partha-narasimhan-duXJOBVg_l4-unsplash.jpg?resize=1920%2C1280&ssl=1'),
(176, 'Slovakia', 'SK', 'A country in Central Europe known for its picturesque mountains, medieval castles, and charming towns.', 'Mountains, Castles, Culture, History, Nature', 'Bratislava', 'Bratislava, Košice, Prešov, Žilina', 'Slovak', 'Euro', 'https://idsb.tmgrup.com.tr/ly/uploads/images/2024/03/18/319978.jpg'),
(177, 'Slovenia', 'SI', 'A country in Central Europe known for its stunning alpine landscapes, picturesque lakes, and charming capital city, Ljubljana.', 'Lakes, Mountains, Culture, Nature, Hospitality', 'Ljubljana', 'Ljubljana, Maribor, Celje, Kranj', 'Slovene', 'Euro', 'https://www.state.gov/wp-content/uploads/2018/11/Slovenia-2560x1395.jpg'),
(178, 'Solomon Islands', 'SB', 'A country in the South Pacific known for its tropical rainforests, coral reefs, and World War II history.', 'Islands, WWII History, Culture, Diving, Nature', 'Honiara', 'Honiara, Auki, Gizo, Kirakira', 'English', 'Solomon Islands Dollar', 'https://www.state.gov/wp-content/uploads/2023/07/shutterstock_1740713318v2-2503x1406.jpg'),
(179, 'Somalia', 'SO', 'A country in the Horn of Africa known for its nomadic culture, beautiful beaches, and ongoing political instability.', 'Culture, Conflict, Hospitality, Coastline, History', 'Mogadishu', 'Mogadishu, Hargeisa, Bosaso, Kismayo', 'Somali, Arabic', 'Somali Shilling', 'https://i.redd.it/0dydsipkd4o51.jpg'),
(180, 'South Africa', 'ZA', 'A country at the southern tip of Africa known for its diverse landscapes, wildlife, and cultural heritage, including Nelson Mandela\'s legacy.', 'Safari, Wildlife, Culture, Beaches, Diversity', 'Bloemfontein, Kaapstad, Pretoria', 'Pretoria, Cape Town, Johannesburg, Durban', 'Afrikaans, English, Zulu, Xhosa', 'South African Rand', 'https://live.southafrica.net/media/282065/de-tafelberg-gezien-vanaf-signal-hill-in-de-zomer.jpg?anchor=center&mode=crop&quality=100&width=1920&height=810&bgcolor=white&rnd=132621698510000000'),
(181, 'South Korea', 'KR', 'A country in East Asia known for its vibrant cities, technological innovation, and rich cultural heritage, including ancient temples and palaces.', 'Technology, Culture, Cuisine, K-pop, Efficiency', 'Seoul', 'Seoul, Busan, Incheon, Daegu', 'Korean', 'South Korean Won', 'https://media.nomadicmatt.com/2022/koreaguide1.jpg'),
(182, 'South Sudan', 'SS', 'A country in East-Central Africa known for its vast plains, wildlife, and ongoing challenges following its independence from Sudan.', 'Wildlife, Culture, Independence, Hospitality, Conflict', 'Juba', 'Juba, Malakal, Wau, Bentiu', 'English', 'South Sudanese Pound', 'https://www.state.gov/wp-content/uploads/2018/11/South-Sudan-e1555938627263-2502x1406.jpg'),
(183, 'Spain', 'ES', 'A country in southwestern Europe known for its rich history, diverse culture, and beautiful Mediterranean beaches.', 'Culture, Cuisine, Beaches, History, Festivals', 'Madrid', 'Madrid, Barcelona, Valencia, Seville', 'Spanish', 'Euro', 'https://imgproxy.natucate.com/wF8RACmH64YN4YV3BSgRXmhB7LtrW2eBW-xf6wRpJmQ/rs:fill/aHR0cHM6Ly93d3cubmF0dWNhdGUuY29tL21lZGlhL3BhZ2VzL3JlaXNlemllbGUvNDI4YTYzZWUtMmYzOS00YmFjLTgwY2UtNmY2N2Y4Yzc1NzJlL2MxNDJhZjc3MWUtMTY3OTQ4Njc1MC9zcGFuaWVuLWxhZW5kZXJpbmZvcm1hdGlvbmVuLXN0YWR0LW96ZWFuLXdhc3Nlci1uYXR1Y2F0ZS5qcGc'),
(184, 'Sri Lanka', 'LK', 'An island nation in South Asia known for its ancient ruins, vibrant culture, and stunning beaches.', 'Beaches, Culture, Wildlife, Tea, Hospitality', 'Colombo', 'Colombo, Kandy, Galle, Negombo', 'Sinhala, Tamil', 'Sri Lankan Rupee', 'https://media.cntraveler.com/photos/64df56c0f3e99758036e9581/16:9/w_2560%2Cc_limit/1288609237'),
(185, 'St Kitts & Nevis', 'KN', 'A Caribbean country known for its beautiful beaches, lush rainforests, and historic sugar plantations.', 'Islands, Beaches, Culture, History, Hospitality', 'Basseterre', 'Basseterre, Charlestown', 'English', 'Eastern Caribbean Dollar', 'https://www.msccruises.nl/-/media/global-contents/destinations/ports/saint-kitts-and-nevis/basseterre/cruise-to-basseterre-saint-kitts-and-nevis.jpg?bc=transparent&as=1&dmc=0&iar=0&mh=1395&mw=2460&sc=0&thn=0&udi=0&hash=8A6CE9A572117D9588E18A46C60D7867'),
(186, 'St Lucia', 'LC', 'A Caribbean island nation known for its dramatic landscapes, including the Pitons, and its vibrant Creole culture.', 'Beaches, Mountains, Culture, Luxury, Hospitality', 'Castries', 'Castries, Gros Islet, Vieux Fort, Micoud', 'English', 'Eastern Caribbean Dollar', 'https://a.travel-assets.com/findyours-php/viewfinder/images/res70/244000/244198-St-Lucia.jpg'),
(187, 'St Vincent', 'VC', 'An island country in the Caribbean known for its volcanic landscapes, lush rainforests, and vibrant culture.', 'Beaches, Islands, Culture, Volcano, Hospitality', 'Kingstown', 'Kingstown, Georgetown, Byera Village', 'English', 'Eastern Caribbean Dollar', 'https://media.audleytravel.com/-/media/images/home/caribbean/st-vincent/country-guides/highlights-of-st-vincent-and-the-grenadines/istock_19667050_st_vincent_and_the_grenadines_salt_whistle_bay_mayreau_letterbox.jpg?q=79&w=1920&h=685'),
(188, 'Sudan', 'SD', 'A country in North-East Africa known for its ancient history, Nile River, and diverse cultures.', 'Desert, Culture, History, Nile, Conflict', 'Khartoum', 'Khartoum, Omdurman, Port Sudan, Kassala', 'Arabic, English', 'Sudanese Pound', 'https://www.rjtravelagency.com/wp-content/uploads/2023/12/Geography-of-Sudan-2.jpg'),
(189, 'Suriname', 'SR', 'A country in South America known for its dense rainforests, diverse wildlife, and vibrant multicultural society.', 'Rainforest, Culture, Diversity, Wildlife, Hospitality', 'Paramaribo', 'Paramaribo, Lelydorp, Nieuw Nickerie, Moengo', 'Dutch', 'Surinamese Dollar', 'https://merk.anwb.nl/transform/7396f62a-e702-408a-aa78-c17f98d94a87/suriname_awarradam-jungle_camp_suriname-rivier_shutterstock?io=height%3A512%2Ctransform%3Afill%2Cwidth%3A3425'),
(190, 'Swaziland', 'SZ', 'A landlocked country in Southern Africa known for its stunning landscapes, wildlife reserves, and Swazi culture.', 'Culture, Wildlife, Mountains, Tradition, Hospitality', 'Mbabane', 'Mbabane, Manzini, Big Bend, Malkerns', 'Swazi, English', 'Swazi Lilangeni, South African Rand', 'https://alloutafrica.com/wp-content/uploads/2018/04/AOA_WEBSITE-TOURS-COVER2-1500x630.jpg'),
(191, 'Sweden', 'SE', 'A Scandinavian country known for its beautiful forests, lakes, and coastal islands, as well as its innovative design and high quality of life.', 'Nature, Culture, Design, History, Innovation', 'Stockholm', 'Stockholm, Gothenburg, Malmö, Uppsala', 'Swedish', 'Swedish Krona', 'https://sweden.se/_next/image?url=https%3A%2F%2Fcms.sweden.se%2Fapp%2Fuploads%2F2021%2F04%2Fklippan-gothenburg.jpg&w=3840&q=75'),
(192, 'Switzerland', 'CH', 'A landlocked country in Central Europe known for its stunning Alps, picturesque lakes, and efficient public transportation system.', 'Alps, Neutrality, Banking, Chocolate, Efficiency', 'Bern', 'Bern, Zurich, Geneva, Basel', 'German, French, Italian, Romansh', 'Swiss Franc', 'https://cdn.britannica.com/65/162465-050-9CDA9BC9/Alps-Switzerland.jpg'),
(193, 'Syria', 'SY', 'A country in Western Asia known for its rich history, ancient ruins, and diverse culture, despite ongoing conflict.', 'History, Culture, Conflict, Hospitality, Cuisine', 'Damascus', 'Damascus, Aleppo, Homs, Hama', 'Arabic', 'Syrian Pound', 'https://www.smb.museum/uploads/tx_smb/exhibitions/exhibition_61384/03_ISL_KulturlandschaftSyrien_Damaskus_Hajjar_WEB_xl.jpg'),
(194, 'Taiwan', 'TW', 'An island nation in East Asia known for its bustling cities, beautiful landscapes, and rich Chinese heritage.', 'Technology, Cuisine, Culture, Mountains, Night Markets', 'Taipei', 'Taipei, Kaohsiung, Taichung, Tainan', 'Mandarin', 'New Taiwan Dollar', 'https://a.travel-assets.com/findyours-php/viewfinder/images/res70/470000/470134-Taipei.jpg'),
(195, 'Tajikistan', 'TJ', 'A landlocked country in Central Asia known for its stunning mountain scenery, ancient cities, and vibrant culture.', 'Mountains, Culture, Hospitality, History, Adventure', 'Dushanbe', 'Dushanbe, Khujand, Kulob, Qurghonteppa', 'Tajik', 'Tajikistani Somoni', 'https://midlifesafaris.com/wp-content/uploads/2019/07/mg_0117-1.jpg'),
(196, 'Tanzania', 'TZ', 'A country in East Africa known for its diverse wildlife, including the Serengeti National Park and Mount Kilimanjaro, the tallest peak in Africa.', 'Safari, Kilimanjaro, Beaches, Wildlife, Culture', 'Dodoma', 'Dodoma, Dar es Salaam, Arusha, Mwanza', 'Swahili, English', 'Tanzanian Shilling', 'https://www.expogr.com/images/tanzania_safari.jpg'),
(197, 'Thailand', 'TH', 'A country in Southeast Asia known for its beautiful beaches, ornate temples, and vibrant street food culture.', 'Beaches, Cuisine, Culture, Temples, Hospitality', 'Bangkok', 'Bangkok, Phuket, Chiang Mai, Pattaya', 'Thai', 'Thai Baht', 'https://media.weflycheap.be/eyJidWNrZXQiOiJ3ZWZseWNoZWFwIiwia2V5IjoiMmEyYWEwYjdmMDBjNDhlYjg4YTFjMjVjMjhhYzgzNjZfdXJsXzIzMjE1LmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6Mzg0MCwiZml0IjoiaW5zaWRlIiwicXVhbGl0eSI6NzV9fX0='),
(198, 'Timor Leste', 'TL', 'A country in Southeast Asia known for its rugged landscapes, diverse culture, and tumultuous history.', 'Timor L\'Este, Dili, Southeast Asia, landscapes, culture', 'Dili', 'Dili, Baucau, Same, Suai', 'Tetum, Portuguese', 'United States Dollar', 'https://www.state.gov/wp-content/uploads/2023/07/shutterstock_1335804755v2.jpg'),
(199, 'Togo', 'TG', 'A country in West Africa known for its palm-lined beaches, traditional villages, and vibrant markets.', 'Culture, Beaches, Hospitality, Wildlife, Music', 'Lomé', 'Lomé, Sokodé, Kara, Kpalimé', 'French', 'West African CFA franc', 'https://media.graphassets.com/resize=width:1600/auto_image/quality=value:85/compress/Cpkk8GzJS7O7fX2Dst9j'),
(200, 'Tonga', 'TO', 'A Polynesian kingdom in the South Pacific known for its pristine beaches, coral reefs, and traditional Tongan culture.', 'Islands, Culture, Hospitality, Diving, Tradition', 'Nuku\'alofa', 'Nuku\'alofa, Neiafu, Haveluloto, Vaini', 'Tongan, English', 'Tongan Pa\'anga', 'https://content.r9cdn.net/rimg/dimg/d5/9f/82812a37-city-54946-16a2fae6f83.jpg?width=1366&height=768&xhint=1960&yhint=935&crop=true'),
(201, 'Trinidad & Tobago', 'TT', 'A twin-island country in the Caribbean known for its carnival celebrations, diverse culture, and lush rainforests.', 'Carnival, Beaches, Culture, Music, Hospitality', 'Port of Spain', 'Port of Spain, Chaguanas, San Fernando, Arima', 'English', 'Trinidad and Tobago Dollar', 'https://www.state.gov/wp-content/uploads/2019/04/Trinidad-and-Tobago-e1556106031676-2503x1406.jpg'),
(202, 'Tunisia', 'TN', 'A country in North Africa known for its ancient ruins, beautiful Mediterranean beaches, and vibrant souks.', 'Desert, Culture, History, Beaches, Ruins', 'Tunis', 'Tunis, Sfax, Sousse, Gabès', 'Arabic', 'Tunisian Dinar', 'https://www.thoughtco.com/thmb/TpYPmMCB9Suyt2rJLJ432loJ09Y=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/view-from-hill-byrsa-with-ancient-remains-of-carthage-and-landscape-700447880-7a934cea8cb447d7bbc6f0d9f84cb0ac.jpg'),
(203, 'Turkey', 'TR', 'A transcontinental country straddling Europe and Asia known for its rich history, stunning architecture, and delicious cuisine.', 'History, Cuisine, Culture, Bosphorus, Hospitality', 'Ankara', 'Ankara, Istanbul, Izmir, Bursa', 'Turkish', 'Turkish Lira', 'https://media.tacdn.com/media/attractions-content--1x-1/11/91/83/ba.jpg'),
(204, 'Turkmenistan', 'TM', 'A country in Central Asia known for its ancient Silk Road cities, desert landscapes, and the fiery Darvaza Gas Crater.', 'Desert, Culture, Gas, History, Hospitality', 'Ashgabat', 'Ashgabat, Turkmenabat, Dasoguz, Mary', 'Turkmen', 'Turkmenistan Manat', 'https://www.state.gov/wp-content/uploads/2023/07/shutterstock_1904359585v2.jpg'),
(205, 'Turks & Caicos', 'TC', 'A British Overseas Territory in the Caribbean known for its stunning beaches, crystal-clear waters, and vibrant coral reefs.', 'Beaches, Islands, Diving, Luxury, Hospitality', 'Cockburn Town', 'Cockburn Town, Providenciales, North Caicos, Middle Caicos', 'English', 'United States Dollar', 'https://bigbluecollective.com/wp-content/uploads/2017/05/boatbeach.jpg'),
(206, 'Tuvalu', 'TV', 'A Polynesian island nation in the South Pacific known for its remote location, pristine beaches, and traditional way of life.', 'Islands, Culture, Fishing, Atolls, Hospitality', 'Funafuti', 'Funafuti', 'Tuvaluan, English', 'Tuvaluan Dollar', 'https://facts.net/wp-content/uploads/2023/07/35-facts-about-tuvalu-1688355579.jpg'),
(207, 'Uganda', 'UG', 'A country in East Africa known for its diverse wildlife, including mountain gorillas, and its lush landscapes.', 'Wildlife, Gorillas, Culture, Nature, Hospitality', 'Kampala', 'Kampala, Gulu, Lira, Jinja', 'English, Swahili', 'Ugandan Shilling', 'https://media.tacdn.com/media/attractions-content--1x-1/12/27/5d/38.jpg'),
(208, 'Ukraine', 'UA', 'A country in Eastern Europe known for its rich history, diverse culture, and beautiful landscapes, including the Carpathian Mountains.', 'History, Culture, Chernobyl, Architecture, Hospitality', 'Kyiv', 'Kyiv, Kharkiv, Odesa, Dnipro', 'Ukrainian', 'Ukrainian Hryvnia', 'https://uploads.exoticca.com/global/destination/poi/kiev.png'),
(209, 'United Arab Emirates', 'AE', 'A federation of seven emirates in the Middle East known for its futuristic cities, luxury shopping, and iconic landmarks such as the Burj Khalifa.', 'Skyscrapers, Luxury, Desert, Culture, Innovation', 'Abu Dhabi', 'Abu Dhabi, Dubai, Sharjah, Ajman', 'Arabic', 'United Arab Emirates Dirham', 'https://cosatravel.ch/wp-content/uploads/2022/06/uae-dubai-desert-skyline-1440x732.jpg'),
(210, 'United Kingdom', 'GB', 'A country in Western Europe known for its historic landmarks, diverse culture, and picturesque countryside.', 'History, Culture, Royalty, Diversity, Innovation', 'London', 'London, Manchester, Birmingham, Edinburgh', 'English', 'British Pound Sterling', 'https://www.27vakantiedagen.nl/wp-content/uploads/2022/05/londen-1250x488.jpg'),
(211, 'United States of America', 'US', 'A country in North America known for its diverse landscapes, vibrant cities, and cultural influence around the world.', 'Diversity, Innovation, Culture, Nature, Power', 'Washington D.C.', 'New York City, Los Angeles, Chicago, Houston', 'English', 'United States Dollar', 'https://www.introducingnewyork.com/f/estados-unidos/nueva-york/guia/nueva-york.jpg'),
(212, 'Uruguay', 'UY', 'A country in South America known for its beautiful beaches, vibrant culture, and historic colonial towns.', 'Beaches, Culture, Wine, Hospitality, Tango', 'Montevideo', 'Montevideo, Salto, Paysandú, Las Piedras', 'Spanish', 'Uruguayan Peso', 'https://static1.mclcm.net/iod/images/v2/103/photo/332377/1200x630_100_300_000000x30x0.jpg?ts=20191114155424'),
(213, 'Uzbekistan', 'UZ', 'A country in Central Asia known for its ancient cities along the Silk Road, stunning mosques, and rich cultural heritage.', 'Silk Road, Culture, History, Architecture, Hospitality', 'Tashkent', 'Tashkent, Samarkand, Bukhara, Urgench', 'Uzbek', 'Uzbekistani Som', 'https://www.intriqjourney.com/wp-content/uploads/2020/07/9D-Legends-of-Uzbekistan-1820x697_c.jpg'),
(214, 'Vanuatu', 'VU', 'A South Pacific island nation known for its volcanic landscapes, pristine beaches, and vibrant Melanesian culture.', 'Islands, Culture, Diving, Nature, Hospitality', 'Port Vila', 'Port Vila, Luganville, Norsup, Port-Olry', 'Bislama, English, French', 'Vanuatu Vatu', 'https://entiretravel.imgix.net/getmedia/4cb1c803-4e8e-429c-971a-fbb91dcddd6d/The-Havannah-Hero-1.jpg?auto=format'),
(215, 'Vatican City', 'VA', 'An independent city-state and the smallest country in the world, known for its iconic landmarks, including St. Peter\'s Basilica and the Sistine Chapel.', 'Religion, Art, History, Pope, Architecture', 'Vatican City', 'Vatican City', 'Italian, Latin', 'Euro', 'https://media1.thrillophilia.com/filestore/d5xediokku3fjm4mc3ew61wrbg19_1580555044_shutterstock_1528726991.jpg'),
(216, 'Venezuela', 'VE', 'A country in northern South America known for its diverse landscapes, including the Andes Mountains and the Amazon rainforest, as well as its rich cultural heritage.', 'Oil, Beaches, Culture, Nature, Hospitality', 'Caracas', 'Caracas, Maracaibo, Valencia, Barquisimeto', 'Spanish', 'Venezuelan Bolívar', 'https://www.ilo.org/sites/default/files/styles/hero_basic_desktop/public/2024-04/50545228161_38dd8a9224_k_0.jpg.webp?itok=Mqgv-PYH'),
(217, 'Vietnam', 'VN', 'A Southeast Asian country known for its stunning natural beauty, ancient temples, and bustling cities.', 'History, Cuisine, Culture, Nature, Hospitality', 'Hanoi', 'Hanoi, Ho Chi Minh City, Da Nang, Hai Phong', 'Vietnamese', 'Vietnamese Dong', 'https://www.asiadirect.nl/wp-content/uploads/2020/10/Vietnam-Halong-Bay-overview.jpg'),
(218, 'US Virgin Islands', 'VI', 'A group of islands in the Caribbean Sea that are an unincorporated territory of the United States, known for their beautiful beaches and rich history.', 'Beaches, Islands, Diving, Hospitality, Nature', 'Charlotte Amalie', 'Charlotte Amalie, Christiansted, Cruz Bay', 'English', 'United States Dollar', 'https://media-cdn.tripadvisor.com/media/photo-m/1280/15/33/f5/57/us-virgin-islands.jpg'),
(219, 'Yemen', 'YE', 'A country in the Middle East known for its ancient history, diverse landscapes, and rich cultural heritage, but also facing ongoing conflict and humanitarian crisis.', 'History, Culture, Architecture, Conflict, Hospitality', 'Sana\'a', 'Sana\'a, Aden, Ta\'izz, Al Hudaydah', 'Arabic', 'Yemeni Rial', 'https://i.natgeofe.com/k/fe1a5003-a47b-4409-a0f6-dacedc806be5/Sanaa_Yemen_KIDS_0521_2x1.jpg'),
(220, 'Zambia', 'ZM', 'A country in Southern Africa known for its stunning Victoria Falls, diverse wildlife, and vast wilderness areas.', 'Wildlife, Victoria Falls, Culture, Nature, Adventure', 'Lusaka', 'Lusaka, Kitwe, Ndola, Kabwe', 'English', 'Zambian Kwacha', 'https://www.intrepidtravel.com/adventures/wp-content/uploads/2018/10/3.-Intrepid-Travel-zambia_victoria-falls-sunset.jpg'),
(221, 'Zimbabwe', 'ZW', 'A landlocked country in Southern Africa known for its diverse landscapes, including the Zambezi River, and its rich cultural heritage.', 'Wildlife, Victoria Falls, Culture, Nature, History', 'Harare', 'Harare, Bulawayo, Chitungwiza, Mutare', 'English, Shona, Ndebele', 'Zimbabwean Dollar', 'https://media.tacdn.com/media/attractions-content--1x-1/12/4e/ef/c2.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` text NOT NULL,
  `picture` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `username`, `password`, `picture`) VALUES
(1, 'Nick', '$2y$10$s.ZuyK/TjcCIupAKut1GJOlvz61CQ7oX1TCM3Dt9QQ6ElWRfO1SFu', 'account.jpg'),
(2, 'Jur', '$2y$10$XjXmBOZg3w11lrF6BzQNL.hZyRlrygaFl99DE8TD9DAsLrgorlDSW', 'account.jpg'),
(4, 'YippeeBug', '$2y$10$a5aWC7PQwhoC/r6N624qw.dOWumYWEXUAe5.q2K8Xkw4aIdrFoJXG', 'account.jpg'),
(5, 'testaccount', '$2y$10$mbdHVS64m42SYzAvFuE/VOur8OvzHIJWrPEFBB9To5TyLV8ZgQCAG', 'account.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `hotels`
--
ALTER TABLE `hotels`
  ADD PRIMARY KEY (`id`),
  ADD KEY `userId` (`userId`);

--
-- Indexes for table `traveladvice`
--
ALTER TABLE `traveladvice`
  ADD PRIMARY KEY (`countryID`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `hotels`
--
ALTER TABLE `hotels`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `traveladvice`
--
ALTER TABLE `traveladvice`
  MODIFY `countryID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=222;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `hotels`
--
ALTER TABLE `hotels`
  ADD CONSTRAINT `hotels_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
